import {expect,test} from '@playwright/test';
import {useSupabaseFixtures} from './support/supabaseFixtures';
const id='50000000-0000-4000-8000-000000000001',job='60000000-0000-4000-8000-000000000001';
const proposal={kind:'job_proposal',id,details:{name:'Example House',jobCode:'EXAMPLE-HOUSE',address:'123 Example St',customerName:null,contactPhone:null,contactEmail:null,notes:'Install four vinyl windows.',startDate:null,endDate:null,projectedHours:200,goalHours:180,squareFeet:null},similarJobs:[]};
const schedule={kind:'schedule_proposal',id,assignmentCount:1,message:'Draft saved.'};
const reviewed={requestId:id,reviewToken:'fresh-token',published:false,issues:[],assignments:[{id:job,job:'EXAMPLE · Example House',startDate:'2026-10-05',endDate:'2026-10-05',status:'draft',crew:[{id:'lead',name:'Alex Lead',role:'foreman'},{id:'crew',name:'River Installer',role:'installer'}]}]};
async function ask(page:import('@playwright/test').Page,artifact:unknown){await page.route('**/functions/v1/ask',r=>r.fulfill({json:{answer:'Review the details below.',artifacts:[artifact]}}));await page.goto('/ask');await page.locator('.ask-input input').fill('Create a job and schedule the crew');await page.locator('.ask-input input').press('Enter');}
for(const width of [390,1440])test(`new-job preview, retry receipt and readable layout at ${width}`,async({page})=>{
 await page.setViewportSize({width,height:960});await useSupabaseFixtures(page,{role:'owner'});let attempts=0;
 await page.route('**/rest/v1/rpc/ai_create_job',r=>{expect(r.request().postDataJSON()).toEqual({p_request:id,p_details:proposal.details});attempts++;return r.fulfill(attempts===1?{status:503,json:{message:'Temporary failure'}}:{json:{projectId:job}});});
 await ask(page,proposal);const card=page.getByRole('region',{name:'Review new job'});await expect(card).toBeVisible();expect(attempts).toBe(0);await page.screenshot({path:`e2e/test-results/ask-action-preview-${width}.png`,fullPage:true});await card.getByRole('button',{name:'Create job'}).click();await expect(card.getByRole('alert')).toBeVisible();await card.getByRole('button',{name:'Create job'}).click();await expect(card.getByRole('status')).toContainText('Job created');await expect(card.getByRole('link',{name:'Open job'})).toHaveAttribute('href',`/projects/${job}`);expect(attempts).toBe(2);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:`e2e/test-results/ask-action-${width}.png`,fullPage:true});
});
test('schedule publication requires fresh review and records the actual result',async({page})=>{
 await useSupabaseFixtures(page,{role:'owner'});let published=0,reads=0;
 await page.route('**/rest/v1/rpc/ai_review_schedule',r=>{reads++;return r.fulfill({json:{...reviewed,issues:reads===1?['A person has approved time off.']:[]}});});
 await page.route('**/rest/v1/rpc/ai_publish_schedule',r=>{expect(r.request().postDataJSON()).toEqual({p_request:id,p_review_token:'fresh-token'});published++;return r.fulfill({json:{published:true,notifications:'queued'}});});
 await ask(page,schedule);const card=page.getByRole('region',{name:'Review crew schedule'});await expect(card.getByRole('button',{name:'Publish this schedule'})).toHaveCount(0);await card.getByRole('button',{name:'Review / refresh availability'}).click();await expect(card).toContainText('Alex Lead');await expect(card.getByRole('button',{name:'Publish this schedule'})).toBeDisabled();expect(published).toBe(0);await card.getByRole('button',{name:'Review / refresh availability'}).click();await expect(card.getByRole('button',{name:'Publish this schedule'})).toBeEnabled();await card.getByRole('button',{name:'Publish this schedule'}).click();await expect(card.getByRole('status')).toContainText('Schedule published');expect(published).toBe(1);
});
test('installer cannot use a stale job-proposal card to create a job',async({page})=>{await useSupabaseFixtures(page,{role:'installer'});await ask(page,proposal);await expect(page.getByRole('button',{name:'Create job'})).toBeDisabled();});
