import { describe, expect, it } from 'vitest';
import { parseActivityCatalog } from './catalog';
const id=(n:number)=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const JOB=id(1),UNIT=id(2),at='2026-10-04T06:00:00.000001Z';
const entry=()=>({definitionId:id(3),definitionVersionId:id(4),position:0,enabled:true,scope:'general',labelEn:'Planning',labelEs:'Planear',machineSelection:false,typedFields:[{id:'ready',label_en:'Ready',label_es:'Listo',type:'boolean',required:true}],eligibleNow:true,ineligibleReason:null as string|null});
const reply=()=>({protocolVersion:1,asOf:at,availability:'available',projectId:JOB,unit:null,selection:{selectionId:id(5),selectionRevision:1,menuVersionId:id(6),eligibleNow:true,activities:[entry()]},totals:{availability:'unavailable',reasonCode:'not_ready'}});
describe('narrow job activity selection',()=>{
  it('keeps exact selection/version/schema IDs and unavailable totals without substituting zero',()=>{const parsed=parseActivityCatalog(reply(),JOB,null);expect(parsed.selection?.activities[0].typedFields[0]).toMatchObject({required:true,type:'boolean'});expect(parsed.selection?.selectionId).toBe(id(5));expect(parsed.totals).toEqual({availability:'unavailable',reasonCode:'not_ready'});expect(parsed).not.toHaveProperty('paidSeconds');});
  it('distinguishes authorized no-menu from source unavailable',()=>{expect(parseActivityCatalog({...reply(),selection:null},JOB,null).availability).toBe('available');expect(parseActivityCatalog({...reply(),availability:'unavailable',projectId:null,unit:null,selection:null},JOB,UNIT).availability).toBe('unavailable');});
  it('never accepts identifiers in a hidden-source result or another job',()=>{expect(()=>parseActivityCatalog({...reply(),availability:'unavailable'},JOB,null)).toThrow();expect(()=>parseActivityCatalog({...reply(),projectId:id(8)},JOB,null)).toThrow();});
  it('holds Specific without an exact authorized unit and accepts its explicit explanation',()=>{const value=reply();value.selection.activities[0]={...entry(),scope:'specific',eligibleNow:false,ineligibleReason:'unit_required'} as ReturnType<typeof entry>;expect(parseActivityCatalog(value,JOB,null).selection?.activities[0].eligibleNow).toBe(false);value.selection.activities[0].eligibleNow=true;value.selection.activities[0].ineligibleReason=null;expect(()=>parseActivityCatalog(value,JOB,null)).toThrow();});
  it('rejects a missing requested unit rather than dropping its context',()=>{expect(()=>parseActivityCatalog(reply(),JOB,UNIT)).toThrow();});
  it('checks menu and enabled flags before accepting an eligible activity',()=>{for(const change of [{enabled:false},{eligibleNow:false},{ineligibleReason:'unknown'}]){const value=reply();Object.assign(value.selection.activities[0],change);expect(()=>parseActivityCatalog(value,JOB,null)).toThrow();}expect(()=>parseActivityCatalog({...reply(),selection:{...reply().selection,eligibleNow:false}},JOB,null)).toThrow();});
  it('refuses duplicate definition/version/position IDs and unordered entries',()=>{for(const second of [{...entry(),position:1},{...entry(),definitionId:id(8),definitionVersionId:id(9)},{...entry(),definitionId:id(8),definitionVersionId:id(9),position:0}]){const value=reply();value.selection.activities.push(second);expect(()=>parseActivityCatalog(value,JOB,null)).toThrow();}});
  it('rejects stale DTO extensions, coercion, fractional revisions and malformed precise timestamps',()=>{for(const value of [{...reply(),drafts:[]},{...reply(),asOf:'2026-10-04T06:00:00.0000001Z'},{...reply(),selection:{...reply().selection,selectionRevision:'1'}},{...reply(),selection:{...reply().selection,selectionRevision:1.1}},{...reply(),totals:{availability:'available',paidSeconds:0}}])expect(()=>parseActivityCatalog(value,JOB,null)).toThrow();});
  it('bounds plain UTF8 input, rejects accessors and preserves Unicode field text',()=>{const value=reply();value.selection.activities[0].labelEn='😀 Planning';expect(parseActivityCatalog(value,JOB,null).selection?.activities[0].labelEn).toBe('😀 Planning');for(const label of ['\ud800','bad\0label','😀'.repeat(121)]){value.selection.activities[0].labelEn=label;expect(()=>parseActivityCatalog(value,JOB,null)).toThrow();}const accessor=Object.defineProperty(reply(),'asOf',{get:()=>at,enumerable:true});expect(()=>parseActivityCatalog(accessor,JOB,null)).toThrow();});
  it('clones nested typed fields rather than retaining caller-mutable intent material',()=>{const value=reply();const parsed=parseActivityCatalog(value,JOB,null);value.selection.activities[0].typedFields[0].required=false;expect(parsed.selection?.activities[0].typedFields[0].required).toBe(true);});
});
