// Forge AI daily log copy. Loads with the lazy Ask page (like fieldCatalog.ts),
// not with the morning app shell. Every key has English and Spanish.
import { useCallback } from "react";
import { useLanguage } from "../../lib/i18n/context";
import type { TKey as AppKey } from "../../lib/i18n/catalog";
import { translate, type CatalogEntry, type TVars } from "../../lib/i18n/translate";

export const AI_DAILY_LOG_CATALOG = {
  "aiLog.title": { en: "Today's daily log", es: "Registro del día" },
  "aiLog.preset": { en: "Build today's daily log", es: "Hacer el registro de hoy" },
  "aiLog.job": { en: "Job", es: "Obra" },
  "aiLog.date": { en: "Date", es: "Fecha" },
  "aiLog.noJob": { en: "Which job is this log for?", es: "¿Para qué obra es este registro?" },
  "aiLog.chooseBetween": { en: "More than one job matches. Which one?", es: "Coinciden varias obras. ¿Cuál es?" },
  "aiLog.useJob": { en: "Use {job}", es: "Usar {job}" },
  "aiLog.pickJob": { en: "Choose a job", es: "Elegir obra" },
  "aiLog.changeJob": { en: "Change job", es: "Cambiar obra" },
  "aiLog.searchJobs": { en: "Search jobs", es: "Buscar obras" },
  "aiLog.chatNamed": { en: "The chat mentioned another job. Nothing moved. Switch this log to it?", es: "En el chat se mencionó otra obra. No se movió nada. ¿Cambiar este registro a esa obra?" },
  "aiLog.shared": { en: "One shared log per job per day. Your entry is added below what is already there; nothing anyone wrote is replaced.", es: "Un registro compartido por obra y día. Tu parte se agrega debajo de lo que ya hay; no se reemplaza nada." },
  "aiLog.answerHelp": { en: "Answer by voice or typing; one message can answer several. Unknown stays unknown.", es: "Responde por voz o escribiendo; un mensaje puede responder varias. Lo desconocido queda como desconocido." },
  "aiLog.field.work_completed": { en: "Work completed", es: "Trabajo terminado" },
  "aiLog.field.units_stages": { en: "Units / stages", es: "Unidades / etapas" },
  "aiLog.field.people": { en: "People involved", es: "Personas" },
  "aiLog.field.problems": { en: "Problems or delays", es: "Problemas o retrasos" },
  "aiLog.field.notes": { en: "Useful notes", es: "Notas útiles" },
  "aiLog.field.day_flow": { en: "How the day went", es: "Cómo fue el día" },
  "aiLog.field.weather": { en: "Weather", es: "Clima" },
  "aiLog.field.went_well": { en: "Went well", es: "Salió bien" },
  "aiLog.field.went_poorly": { en: "Went poorly", es: "Salió mal" },
  "aiLog.field.would_have_helped": { en: "Would have helped", es: "Habría ayudado" },
  "aiLog.field.what_worked": { en: "What worked", es: "Qué funcionó" },
  "aiLog.required": { en: "required", es: "obligatorio" },
  "aiLog.status.captured": { en: "Answered", es: "Respondido" },
  "aiLog.status.unknown": { en: "Said unknown", es: "Dijo que no sabe" },
  "aiLog.status.missing": { en: "Still needed", es: "Falta" },
  "aiLog.source.said": { en: "you said", es: "lo dijiste" },
  "aiLog.source.typed": { en: "you typed", es: "lo escribiste" },
  "aiLog.source.job_clock": { en: "from job clock", es: "del reloj de trabajo" },
  "aiLog.source.unit_records": { en: "from unit records", es: "de los registros de unidades" },
  "aiLog.source.earlier_log": { en: "from earlier log", es: "del registro anterior" },
  "aiLog.markUnknown": { en: "I don't know", es: "No sé" },
  "aiLog.clear": { en: "Clear", es: "Borrar" },
  "aiLog.moreDetails": { en: "More (optional): day, weather, reflections", es: "Más (opcional): día, clima, reflexiones" },
  "aiLog.flow.smooth": { en: "Smooth", es: "Bien" },
  "aiLog.flow.fine": { en: "Fine", es: "Regular" },
  "aiLog.flow.stuck": { en: "Stuck", es: "Trabado" },
  "aiLog.suggestion": { en: "Known: {value}", es: "Dato conocido: {value}" },
  "aiLog.useSuggestion": { en: "Use this", es: "Usar esto" },
  "aiLog.existing": { en: "Already in this log", es: "Ya está en este registro" },
  "aiLog.existingBy": { en: "Started by {name}", es: "Iniciado por {name}" },
  "aiLog.noExisting": { en: "Nobody has filed this job's log for this day yet. Yours starts it.", es: "Nadie ha hecho el registro de esta obra para este día. El tuyo lo empieza." },
  "aiLog.checkingLog": { en: "Checking what the log already says…", es: "Revisando lo que ya dice el registro…" },
  "aiLog.logLoadFailed": { en: "Could not check the shared log. You can save once it loads.", es: "No se pudo revisar el registro compartido. Podrás guardar cuando cargue." },
  "aiLog.checkAgain": { en: "Check again", es: "Revisar otra vez" },
  "aiLog.addition": { en: "Your entry (added exactly like this)", es: "Tu parte (se agrega exactamente así)" },
  "aiLog.photos": { en: "Photos", es: "Fotos" },
  "aiLog.takePhoto": { en: "Take photo", es: "Tomar foto" },
  "aiLog.choosePhotos": { en: "Choose photos", es: "Elegir fotos" },
  "aiLog.photoDestination": { en: "Goes to {job}", es: "Va a {job}" },
  "aiLog.photoNoJob": { en: "No job yet — choose one", es: "Sin obra — elige una" },
  "aiLog.photoOtherJob": { en: "This photo goes to {job}, not this log's job. Move it or remove it.", es: "Esta foto va a {job}, no a la obra de este registro. Muévela o quítala." },
  "aiLog.moveHere": { en: "Move to {job}", es: "Mover a {job}" },
  "aiLog.remove": { en: "Remove", es: "Quitar" },
  "aiLog.caption": { en: "Caption (optional)", es: "Descripción (opcional)" },
  "aiLog.photoHint": { en: "Photos stay on this phone until you save. A photo shows the job; it does not prove what work was done.", es: "Las fotos se quedan en este teléfono hasta que guardes. Una foto muestra la obra; no prueba qué trabajo se hizo." },
  "aiLog.photoLimit": { en: "Up to {n} photos per entry.", es: "Hasta {n} fotos por entrada." },
  "aiLog.reject.not_image": { en: "{name} is not a picture.", es: "{name} no es una imagen." },
  "aiLog.reject.unreadable": { en: "{name} could not be opened on this phone. Try a JPG or take it again.", es: "{name} no se pudo abrir en este teléfono. Prueba un JPG o tómala otra vez." },
  "aiLog.reject.too_large": { en: "{name} is too large to keep. Take a smaller photo.", es: "{name} es demasiado grande. Toma una foto más pequeña." },
  "aiLog.reject.not_kept": { en: "{name} could not be kept on this phone (storage may be full).", es: "{name} no se pudo guardar en este teléfono (puede estar lleno)." },
  "aiLog.photo.on_phone": { en: "Waiting on this phone", es: "Esperando en este teléfono" },
  "aiLog.photo.uploading": { en: "Uploading…", es: "Subiendo…" },
  "aiLog.photo.waiting_signal": { en: "Waiting for signal", es: "Esperando señal" },
  "aiLog.photo.saved": { en: "Saved to the job", es: "Guardada en la obra" },
  "aiLog.photo.failed": { en: "Did not upload — still on this phone", es: "No se subió — sigue en este teléfono" },
  "aiLog.photo.checking": { en: "Checking with the server…", es: "Revisando con el servidor…" },
  "aiLog.retryPhoto": { en: "Try again", es: "Intentar otra vez" },
  "aiLog.problem.no_work": { en: "Say or type what work was completed.", es: "Di o escribe qué trabajo se terminó." },
  "aiLog.problem.no_job": { en: "Choose the job first.", es: "Primero elige la obra." },
  "aiLog.problem.log_not_checked": { en: "Waiting to see what the shared log already says.", es: "Esperando ver lo que ya dice el registro compartido." },
  "aiLog.problem.photo_without_job": { en: "A photo has no job yet.", es: "Una foto no tiene obra." },
  "aiLog.save": { en: "Save daily log", es: "Guardar registro" },
  "aiLog.saving": { en: "Saving…", es: "Guardando…" },
  "aiLog.tryAgain": { en: "Try saving again", es: "Intentar guardar otra vez" },
  "aiLog.notice.stale": { en: "Someone else added to this log while you were working. Nothing of yours was saved yet. Read what is there now, then save again.", es: "Alguien agregó a este registro mientras trabajabas. Todavía no se guardó nada tuyo. Lee lo que hay ahora y guarda otra vez." },
  "aiLog.notice.uncertain": { en: "No answer from the server. It may or may not have saved. Your entry is kept on this phone; saving again cannot add it twice.", es: "El servidor no respondió. Puede que se haya guardado o no. Tu parte queda en este teléfono; guardar otra vez no la agrega dos veces." },
  "aiLog.notice.rejected": { en: "Not saved: {message}", es: "No se guardó: {message}" },
  "aiLog.notDurable": { en: "This browser cannot keep drafts after it closes. Save before leaving.", es: "Este navegador no guarda borradores al cerrarse. Guarda antes de salir." },
  "aiLog.frozen": { en: "Saving these exact words. Editing opens again if the server says no.", es: "Se están guardando estas palabras exactas. Podrás editar otra vez si el servidor dice que no." },
  "aiLog.receipt.saved": { en: "Saved to the {job} log for {date}.", es: "Guardado en el registro de {job} del {date}." },
  "aiLog.receipt.already": { en: "Already saved — this is the entry from your first tap. Not added twice.", es: "Ya estaba guardado — es la entrada de tu primer toque. No se agregó dos veces." },
  "aiLog.receipt.started": { en: "You started this day's log.", es: "Tú empezaste el registro de este día." },
  "aiLog.receipt.added": { en: "Added to the log started by {name}.", es: "Agregado al registro que empezó {name}." },
  "aiLog.receipt.when": { en: "Saved at {time} by {name}. Entry {id}.", es: "Guardado a las {time} por {name}. Entrada {id}." },
  "aiLog.receipt.photosSeparate": { en: "The log is saved. Each photo below shows its own status.", es: "El registro está guardado. Cada foto abajo muestra su propio estado." },
  "aiLog.openLog": { en: "Open the job's logs", es: "Abrir los registros de la obra" },
  "aiLog.startOver": { en: "Start another entry", es: "Empezar otra entrada" },
  "aiLog.discardDraft": { en: "Discard this draft", es: "Descartar este borrador" },
  "aiLog.discardConfirm": { en: "Discard this draft and its photos from this phone? Nothing has been saved.", es: "¿Descartar este borrador y sus fotos de este teléfono? No se ha guardado nada." },
  "aiLog.answerByVoice": { en: "Answer by voice", es: "Responder por voz" },
  "aiLog.workDate": { en: "Work date", es: "Fecha del trabajo" },
  "aiLog.storageError": { en: "Your latest changes are on screen but this phone could not keep them. Keep this screen open; they are saved to the phone again with your next change.", es: "Tus últimos cambios están en pantalla pero el teléfono no pudo guardarlos. Deja esta pantalla abierta; se vuelven a guardar con tu próximo cambio." },
  "aiLog.blockedByAccount": { en: "Not sent: this phone is signed in as someone else now. The entry is kept for the person who wrote it.", es: "No se envió: el teléfono tiene otra sesión ahora. La entrada queda guardada para quien la escribió." },
  "aiLog.preparing": { en: "Preparing {n} photo(s)… Save waits until they are ready.", es: "Preparando {n} foto(s)… Guardar espera a que estén listas." },
  "aiLog.problem.bad_date": { en: "Choose a work date that is today or earlier.", es: "Elige una fecha de trabajo de hoy o anterior." },
  "aiLog.problem.too_long": { en: "This entry is {length} characters; the log takes up to {max}. Shorten it — nothing is cut off for you.", es: "Esta entrada tiene {length} caracteres; el registro admite hasta {max}. Acórtala; no se corta nada automáticamente." },
  "aiLog.reject.too_many": { en: "{name} was not added: this entry already has the most photos it can take.", es: "{name} no se agregó: esta entrada ya tiene el máximo de fotos." },
  "aiLog.reject.draft_closed": { en: "{name} was not added: that entry was closed while it was being prepared.", es: "{name} no se agregó: esa entrada se cerró mientras se preparaba." },
  "aiLog.unsentBlocked": { en: "{n} photo(s) of this saved entry are still only on this phone. Try them again before starting another entry.", es: "{n} foto(s) de esta entrada guardada siguen solo en este teléfono. Vuelve a intentarlas antes de empezar otra entrada." },
  "aiLog.discardUnsent": { en: "Discard {n} photo(s) not uploaded and start another entry", es: "Descartar {n} foto(s) sin subir y empezar otra entrada" },
  "aiLog.discardUnsentConfirm": { en: "Delete {n} photo(s) that never uploaded from this phone? They are not saved anywhere else.", es: "¿Borrar de este teléfono {n} foto(s) que nunca se subieron? No están guardadas en ningún otro lugar." },
  "aiLog.sendAgain": { en: "Not on the server — send again from this phone", es: "No está en el servidor — enviar otra vez desde este teléfono" },
  "aiLog.retryStorage": { en: "Try keeping it on this phone again", es: "Intentar guardarlo otra vez en este teléfono" },
  "aiLog.notice.source_limit": { en: "This entry already lists 50 Ask messages, so the last answer was NOT added (its message could not be recorded with it). Keep those words as your own typed text, or save this entry and start another.", es: "Esta entrada ya tiene 50 mensajes de Ask, así que la última respuesta NO se agregó (su mensaje no se podía registrar). Conserva esas palabras como texto tuyo, o guarda esta entrada y empieza otra." },
  "aiLog.keepHeld": { en: "Keep those words as my typed text", es: "Conservar esas palabras como mi texto" },
  "aiLog.loading": { en: "Opening your draft…", es: "Abriendo tu borrador…" },
  "aiLog.signIn": { en: "Sign in to build a daily log.", es: "Inicia sesión para hacer un registro." },
} as const satisfies Record<string, CatalogEntry>;
export type AiLogKey = keyof typeof AI_DAILY_LOG_CATALOG;
export type TKey = AppKey | AiLogKey;
export type TFn = (key: TKey, vars?: TVars) => string;
export function useAiLogT(): TFn {
  const { lang, t } = useLanguage();
  return useCallback((key: TKey, vars?: TVars) => key.startsWith("aiLog.")
    ? translate(AI_DAILY_LOG_CATALOG, lang, key, vars)
    : t(key as AppKey, vars), [lang, t]);
}
