/**
 * "Remove this login and start fresh" — which of the two things actually
 * happens, and how it is said in plain English.
 *
 * WHY THIS IS TWO SHAPES AND NOT ONE. The owner asked for the ability to
 * delete an account outright. That is exactly right for the case he was
 * describing — a login typed wrong, a person who never showed up, a duplicate
 * — and exactly wrong for a person who worked here. `profiles.id` references
 * `auth.users(id) ON DELETE CASCADE` (20260715240000_crew_dispatch.sql), so
 * deleting the auth user deletes the profile, and from there:
 *
 *   CASCADE — the rows go with it. time_shifts (payroll), receipts, pay_rates,
 *     certifications, toolbox_completions, points_ledger, task_sessions,
 *     project_messages, summon_helpers. A paycheck dispute two years from now
 *     would have nothing to read.
 *   SET NULL — the row survives with nobody on it. install_events.installer_id
 *     and .credited_to: the window stays installed and nobody installed it.
 *   RESTRICT (no ON DELETE clause at all) — the delete simply FAILS.
 *     unit_sessions.profile_id, unit_redos.pressed_by, daily_logs.filed_by,
 *     summons.requested_by, opening_phases.started_by/.submitted_by,
 *     time_shift_edits.edited_by, flash_run_assignments.assigned_by.
 *
 * So the decision is made by the data, not by the person pressing the button:
 * count the rows first. Nothing on file → the hard delete is safe and the
 * email is genuinely free. Anything on file → nothing is deleted, ever; the
 * login is closed and the profile is marked retired instead.
 *
 * WHY THE EMAIL IS RENAMED RATHER THAN THE ROW DELETED. The point of the
 * feature is "start fresh": the same person (or the same address) must be able
 * to be invited again and land on a NEW account. Supabase Auth holds emails
 * unique across auth.users, so a banned account keeps its address hostage
 * forever — `create_invite` would answer "that email already has an account"
 * and there would be no way past it. Renaming the banned user's address to a
 * tombstone (`<uid>@removed.invalid`) frees the real address without touching
 * one row of history: every record still points at the same profile id, which
 * is what every join in this database is keyed on. `.invalid` is the RFC 2606
 * reserved TLD — it can never be a real mailbox, so a tombstone cannot collide
 * with anybody's address, and the uid guarantees two tombstones never collide
 * with each other.
 *
 * Shared by the edge function (manage-crew-access, action `purge_login`) and
 * the Crew access screen, so the sentence the owner reads before he presses
 * the button is generated by the same code that decides what to do — the
 * screen cannot promise one thing while the server does another.
 */

/** One count the server takes before deciding. */
export interface HistoryProbe {
  /** Table to count in. */
  table: string;
  /** The column holding a profile id. */
  column: string;
  /** Plain English for one row, and for many. */
  one: string;
  many: string;
}

/**
 * Every table a person's work, money or safety record lives in.
 *
 * COMPLETENESS RULE, so this list can be checked rather than trusted: every
 * RESTRICT foreign key to `profiles` in the schema is in here (there are eight
 * such columns, listed in the header), because a hard delete would otherwise
 * fail outright; every CASCADE one whose rows are a record of work, money or
 * safety is in here, because a hard delete would silently take them. Columns
 * that are SET NULL and merely decorative — `updated_by`, `resolved_by`,
 * `granted_by` and friends — are deliberately NOT here: losing "who ticked
 * this box" is not losing a record of somebody's work, and a person whose only
 * trace is one of those is exactly the mistyped login this feature is for.
 *
 * Order matters only for the sentence: the first non-zero counts are the ones
 * named, so the heaviest, most recognisable records come first.
 */
export const WORK_HISTORY_PROBES: readonly HistoryProbe[] = [
  { table: "time_shifts", column: "profile_id", one: "punch", many: "punches" },
  {
    table: "unit_sessions",
    column: "profile_id",
    one: "work session",
    many: "work sessions",
  },
  {
    table: "install_events",
    column: "installer_id",
    one: "install",
    many: "installs",
  },
  {
    table: "install_events",
    column: "credited_to",
    one: "credited install",
    many: "credited installs",
  },
  { table: "receipts", column: "uploaded_by", one: "receipt", many: "receipts" },
  { table: "pay_rates", column: "profile_id", one: "pay rate", many: "pay rates" },
  {
    table: "certifications",
    column: "profile_id",
    one: "safety card",
    many: "safety cards",
  },
  {
    table: "toolbox_completions",
    column: "profile_id",
    one: "signed safety talk",
    many: "signed safety talks",
  },
  { table: "daily_logs", column: "filed_by", one: "day log", many: "day logs" },
  {
    table: "opening_phases",
    column: "started_by",
    one: "flashing run",
    many: "flashing runs",
  },
  {
    table: "opening_phases",
    column: "submitted_by",
    one: "finished flashing run",
    many: "finished flashing runs",
  },
  {
    table: "flash_run_assignments",
    column: "assigned_by",
    one: "flashing hand-out",
    many: "flashing hand-outs",
  },
  {
    table: "summons",
    column: "requested_by",
    one: "call for help",
    many: "calls for help",
  },
  {
    table: "summon_helpers",
    column: "profile_id",
    one: "time helping somebody",
    many: "times helping somebody",
  },
  {
    table: "unit_redos",
    column: "pressed_by",
    one: "redo",
    many: "redos",
  },
  {
    table: "time_shift_edits",
    column: "edited_by",
    one: "timecard edit",
    many: "timecard edits",
  },
  {
    table: "points_ledger",
    column: "profile_id",
    one: "points entry",
    many: "points entries",
  },
  {
    table: "task_sessions",
    column: "profile_id",
    one: "tracked task",
    many: "tracked tasks",
  },
  {
    table: "project_messages",
    column: "author_id",
    one: "chat message",
    many: "chat messages",
  },
] as const;

/** `table.column` → how many rows this person has there. */
export type HistoryCounts = Record<string, number>;

/** The key a probe's count is filed under. */
export function probeKey(probe: HistoryProbe): string {
  return `${probe.table}.${probe.column}`;
}

/**
 * Does this person have anything on file worth keeping?
 *
 * Deliberately reads the WHOLE counts object, not just the probes it knows
 * about: a count the server took for a table this file has not heard of still
 * means "there is something here", and the safe answer to a surprise is always
 * "keep it". A count that failed to be taken must be passed in as a positive
 * number or not at all — never as 0 — see the edge function.
 */
export function hasWorkHistory(counts: HistoryCounts): boolean {
  return Object.values(counts).some((n) => Number(n) > 0);
}

/** Which of the two things happens. Named for what the owner will read back. */
export type PurgeShape = "deleted" | "retired";

export function shapeFor(counts: HistoryCounts): PurgeShape {
  return hasWorkHistory(counts) ? "retired" : "deleted";
}

/** `<uid>@removed.invalid` — see the header on why a tombstone, not a delete. */
export function tombstoneEmail(userId: string): string {
  return `${userId}@removed.invalid`;
}

/** Would this address be one of ours? Used to keep a tombstone out of the UI. */
export function isTombstoneEmail(email: string | null | undefined): boolean {
  return /@removed\.invalid$/i.test((email ?? "").trim());
}

/** "14 punches", "1 receipt" — a count in words, for the sentence below. */
function countInWords(probe: HistoryProbe, n: number): string {
  return `${n} ${n === 1 ? probe.one : probe.many}`;
}

/**
 * The non-zero counts, heaviest first, at most `limit` of them.
 *
 * `limit` exists because the sentence is read on a phone: "14 punches, 3
 * receipts and 2 safety cards" is a sentence, and the same line carrying all
 * nineteen probes is a wall.
 */
export function historyHighlights(
  counts: HistoryCounts,
  limit = 3,
): { key: string; words: string }[] {
  const out: { key: string; words: string }[] = [];
  for (const probe of WORK_HISTORY_PROBES) {
    const n = Number(counts[probeKey(probe)] ?? 0);
    if (n > 0) out.push({ key: probeKey(probe), words: countInWords(probe, n) });
    if (out.length >= limit) break;
  }
  return out;
}

/** "a, b and c" — the English list, not the comma-spliced one. */
function joinWords(parts: string[]): string {
  if (parts.length <= 1) return parts[0] ?? "";
  return `${parts.slice(0, -1).join(", ")} and ${parts[parts.length - 1]}`;
}

/**
 * The whole sentence the confirm sheet shows, so the owner knows which of the
 * two things he is about to do BEFORE he does it — never a generic "are you
 * sure".
 *
 * English only on purpose: Crew access is an owner screen, like the rest of
 * this file's callers. See the PR body.
 */
export function removalSentence(
  displayName: string | null | undefined,
  counts: HistoryCounts,
): string {
  const name = (displayName ?? "").trim() || "This person";
  if (!hasWorkHistory(counts)) {
    return `Nothing on file for ${name} — the account will be deleted and the email freed.`;
  }
  const shown = historyHighlights(counts);
  const listed = joinWords(shown.map((h) => h.words));
  const total = Object.values(counts).filter((n) => Number(n) > 0).length;
  const more = total > shown.length ? ", and more," : "";
  return (
    `${name} has ${listed}${more} on file — the login will be closed, ` +
    `the email freed, and every record kept under their name.`
  );
}

/** What the owner reads after it happened. */
export function removalResultSentence(
  displayName: string | null | undefined,
  shape: PurgeShape,
): string {
  const name = (displayName ?? "").trim() || "That login";
  return shape === "deleted"
    ? `${name}'s account is gone and the email is free to use again.`
    : `${name} can't sign in any more, the email is free to use again, and every record is still filed under their name.`;
}
