-- Seed real, domain-accurate tips + watch-outs for the 10 most common catalog
-- types so the installer brain card is never blank on day one. Content is drawn
-- from the St. George Windows gold-standard nail-fin install walkthrough.
-- Idempotent: only fills types whose tips are still empty (never clobbers
-- AI-synthesized tips generated later from real installs).
update window_types wt set
  tips_json = v.tips::jsonb,
  watch_outs_json = v.watch::jsonb,
  difficulty_rating = coalesce(wt.difficulty_rating, v.diff)
from (values
  ('SH3252', $j$["Find the drain slots on the bottom of the frame - that side faces OUT. Never set it drain-side in.","Flash both sides before you set the window; roll the TOP flashing last, over the flange lip, so water sheds down.","Caulk the flanges left, right and top only - leave the bottom open so trapped water can drain.","Shim and level first, center second. Level always wins. Set screws through the flanges, then pull the shims.","St. George standard: caulk off the top and side weep holes, leave the bottom drains open."]$j$, $j$["Out-of-level wall: shim to true level even if the reveal looks uneven - flag the foreman if it is more than ~1 in off.","Confirm stucco vs rock before setting depth - it changes the setout ~1 in (rock) vs ~1.5 in (stucco).","Vinyl softens in high heat - do not overdrive screws or force a bind on hot days."]$j$, 1),
  ('DH3252', $j$["Drain slots on the bottom face OUT - confirm before lifting it in.","Flash the sides first, top flashing last over the flange lip.","Caulk flanges left/right/top, never the bottom - the bottom has to drain.","Level first, then center. Set the flange screws, then remove the shims.","Check both sashes slide before you screw off - a racked frame binds a double-hung fast."]$j$, $j$["Do not seal the bottom weep holes - a double-hung will pond water if you do.","Confirm stucco vs rock setout before install.","On hot days ease off screw torque on vinyl frames."]$j$, 2),
  ('CAS3048', $j$["Drain side faces OUT. Flash sides before setting, top flashing last over the flange.","Level is critical on a casement - if it is out, the sash will not seal or will swing on its own.","Caulk flanges left/right/top only; leave the bottom for drainage.","Set screws through the flange after leveling, then pull the shims and check the sash swings clean.","Test the crank through full travel before you finish caulk."]$j$, $j$["A casement that is not dead level will not latch - do not rush the level step.","Confirm setout depth (stucco vs rock) up front.","Watch the sash edge for scratches when unpackaging with a utility knife."]$j$, 2),
  ('SL6048', $j$["This is a 2-person lift - use suction cups or straps. Set the bottom into the frame, then tilt up.","Get it dead level before screwing off or the panels will not roll smoothly.","Drain side out; flash sides first, top flashing last over the flange lip.","Caulk flanges left/right/top, leave the bottom to drain.","Roll both panels full travel before final caulk to confirm no bind."]$j$, $j$["A racked slider binds - level and square matter more here than on a small window.","Never get under a suspended panel during the lift.","Confirm stucco vs rock setout before setting depth."]$j$, 3),
  ('SL7248', $j$["Large slider - plan a 2-person lift with the suction machine; never solo it.","Level and square are everything - test-roll the panels before you commit screws.","Drain out; flash the sides, then top flashing last over the flange.","Shim to level, set flange screws, pull shims, re-check the roll.","Caulk flanges left/right/top only; leave the bottom open."]$j$, $j$["Heavy glass - keep everyone clear of the drop zone and the suction path.","A slightly racked large slider will not seal or roll - do not accept it.","Confirm the suction-cup machine is on site before scheduling this unit."]$j$, 4),
  ('PIC4848', $j$["Stationary unit - no moving parts, so the finish caulk is the whole quality story.","Drain side out; flash sides first, top flashing last over the flange lip.","Level and center - with no sash to hide it, an out-of-level picture window shows.","Exterior finish caulk is permanent: tape a ~3/4 in gap, caulk, then tool one smooth line.","Photograph the finished caulk line and that all tape/stickers are removed."]$j$, $j$["Sloppy tooling on the exterior caulk is the most common callback on picture windows.","Confirm setout depth (stucco vs rock).","Big glass = 2-person lift; keep clear of the drop zone."]$j$, 2),
  ('PIC6048', $j$["Stationary - the exterior caulk finish is the whole job quality; take your time tooling it.","2-person lift; set the bottom in, tilt up, drain side facing out.","Flash sides first, top flashing last over the flange lip.","Level and center; caulk flanges left/right/top, leave the bottom to drain.","Photograph the final caulk line and confirm tape/stickers removed."]$j$, $j$["Tooling quality varies by installer - a bumpy caulk line is a visible defect.","Confirm stucco vs rock setout.","Keep clear of suspended glass during the lift."]$j$, 3),
  ('AWN3024', $j$["Drain side out; flash sides first, top flashing last over the flange.","Level matters - an awning that is off will not seal against the frame when cranked shut.","Caulk flanges left/right/top only; leave the bottom to drain.","Set flange screws after leveling, pull shims, then crank through full travel.","Confirm the arm hardware operates smoothly before final caulk."]$j$, $j$["An out-of-level awning leaks at the hinge side - level carefully.","Confirm setout depth up front.","Do not force vinyl on hot days."]$j$, 2),
  ('HOP3024', $j$["Hopper opens inward at the top - confirm swing clearance inside before setting.","Drain side out; flash sides first, top flashing last over the flange lip.","Level first - a racked hopper will not seal at the sill.","Caulk flanges left/right/top, leave the bottom to drain.","Test the latch and full open/close before final caulk."]$j$, $j$["Common in basements/wells - verify the well drains so the unit does not sit in water.","Confirm setout depth (stucco vs rock).","Do not seal the bottom weep holes."]$j$, 2),
  ('BAY7248', $j$["Bay is a structural, 3-person unit - it needs support below and cable/knee bracing above per plan.","Confirm the head board and support brackets are in before you hang any weight.","Flash the full perimeter carefully; the roof/seat connections are the leak risk, not just the flanges.","Level and center the center lite first, then bring the flankers to it.","Seal the seat and roof junctions and photograph every flashing/caulk joint."]$j$, $j$["Bays fail from under-support and roof-junction leaks - never skip the bracing or seat flashing.","3-person job with heavy glass - stage the lift and keep the drop zone clear.","Confirm the opening framing and setout with the foreman before starting - bays are non-starters if the rough opening is wrong."]$j$, 5)
) as v(code, tips, watch, diff)
where wt.type_code = v.code
  and jsonb_array_length(coalesce(wt.tips_json, '[]'::jsonb)) = 0;
