// Lesson write-up copy loads with the lazy Ask page, like fieldCatalog.ts.
import { useCallback } from "react";
import { useLanguage } from "../../lib/i18n/context";
import { translate, type CatalogEntry, type TVars } from "../../lib/i18n/translate";

export const LEARNING_CATALOG = {
  "learn.title": { en: "Lesson write-up", es: "Lección del trabajo" },
  "learn.help": { en: "Say what happened in your own words, by voice or text. Mark anything you do not know as Unknown.", es: "Di lo que pasó con tus palabras, por voz o texto. Marca como Desconocido lo que no sepas." },
  "learn.heading.issue": { en: "Issue", es: "Problema" },
  "learn.heading.what_happened": { en: "What happened", es: "Qué pasó" },
  "learn.heading.impact": { en: "Impact", es: "Impacto" },
  "learn.heading.lesson_learned": { en: "Lesson learned", es: "Lección aprendida" },
  "learn.heading.preventive_action": { en: "Preventive action", es: "Acción preventiva" },
  "learn.unknown": { en: "Unknown", es: "Desconocido" },
  "learn.markUnknown": { en: "I don't know", es: "No sé" },
  "learn.notAnswered": { en: "Not answered yet", es: "Sin responder" },
  "learn.missing": { en: "{count} still needed", es: "Faltan {count}" },
  "learn.complete": { en: "Every heading answered or marked Unknown", es: "Todo respondido o marcado como Desconocido" },
  "learn.impactMinutes": { en: "Time lost (minutes, your estimate)", es: "Tiempo perdido (minutos, tu estimado)" },
  "learn.impactCost": { en: "Cost (dollars, your estimate)", es: "Costo (dólares, tu estimado)" },
  "learn.selfReported": { en: "self-reported: {parts}", es: "estimado por quien reporta: {parts}" },
  "learn.minutes": { en: "{count} min", es: "{count} min" },
  "learn.impactNote": { en: "Your estimate only. It never changes your time, pay or anyone's clock.", es: "Solo tu estimado. Nunca cambia tu tiempo, tu pago ni ningún reloj." },
  "learn.job": { en: "Job", es: "Obra" },
  "learn.unit": { en: "Unit", es: "Unidad" },
  "learn.wholeJob": { en: "Whole job", es: "Toda la obra" },
  "learn.original": { en: "Original words", es: "Palabras originales" },
  "learn.originalAnswer": { en: "Original Ask answer", es: "Respuesta original de Ask" },
  "learn.recording": { en: "Play the original recording", es: "Escuchar la grabación original" },
  "learn.recordingUnavailable": { en: "The recording could not be opened.", es: "No se pudo abrir la grabación." },
  "learn.reviewer": { en: "Reviewer (foreman, supervisor or owner)", es: "Revisor (capataz, supervisor o dueño)" },
  "learn.reviewerSearch": { en: "Type a name", es: "Escribe un nombre" },
  "learn.reviewerFind": { en: "Find", es: "Buscar" },
  "learn.reviewerExact": { en: "Matches {name} exactly.", es: "Coincide exactamente con {name}." },
  "learn.reviewerChoose": { en: "More than one person could match \"{name}\". Choose one.", es: "Más de una persona puede coincidir con \"{name}\". Elige una." },
  "learn.reviewerNone": { en: "Nobody who can review this job matches \"{name}\". Choose from the list.", es: "Nadie que pueda revisar esta obra coincide con \"{name}\". Elige de la lista." },
  "learn.reviewerRequired": { en: "Choose who reviews it.", es: "Elige quién lo revisa." },
  "learn.reviewerGone": { en: "{name} can no longer review this. Choose someone else and send again.", es: "{name} ya no puede revisarlo. Elige a otra persona y envíalo otra vez." },
  "learn.role.foreman": { en: "Foreman", es: "Capataz" },
  "learn.role.supervisor": { en: "Supervisor", es: "Supervisor" },
  "learn.role.owner": { en: "Owner", es: "Dueño" },
  "learn.conflict": { en: "This write-up changed on another screen, or a saved change did not go through. Nothing was sent. Review the latest before sending.", es: "Esta lección cambió en otra pantalla, o un cambio guardado no se aplicó. No se envió nada. Revisa lo más reciente antes de enviar." },
  "learn.reloadLatest": { en: "Show the latest version (my unsent change is set aside)", es: "Mostrar la versión más reciente (mi cambio no enviado queda aparte)" },
  "learn.replacedWords": { en: "My words that were set aside (to copy)", es: "Mis palabras que quedaron aparte (para copiar)" },
  "learn.sources": { en: "Original messages ({count})", es: "Mensajes originales ({count})" },
  "learn.sourceRecording": { en: "Play recording {n}", es: "Escuchar grabación {n}" },
  "learn.save": { en: "Save draft", es: "Guardar borrador" },
  "learn.send": { en: "Send to {name}", es: "Enviar a {name}" },
  "learn.sendNeedsReviewer": { en: "Send for review", es: "Enviar a revisión" },
  "learn.resend": { en: "Send to {name} instead", es: "Enviar a {name} en su lugar" },
  "learn.sendBlockedMissing": { en: "Answer or mark Unknown every heading before sending.", es: "Responde o marca como Desconocido cada punto antes de enviar." },
  "learn.sendBlockedIssue": { en: "Say what the issue was and what happened before sending.", es: "Di cuál fue el problema y qué pasó antes de enviar." },
  "learn.sendNeedsConnection": { en: "Sending needs a connection. Your draft is kept.", es: "Enviar necesita conexión. Tu borrador queda guardado." },
  "learn.sendWaitSync": { en: "Your latest draft has not reached Forge yet. Let it sync, then send.", es: "Tu último borrador todavía no llega a Forge. Deja que se sincronice y luego envía." },
  "learn.state.local": { en: "Saved on this phone — not sent", es: "Guardado en este teléfono; no enviado" },
  "learn.state.draft": { en: "Draft saved in Forge — not sent", es: "Borrador guardado en Forge; no enviado" },
  "learn.state.submitted": { en: "Sent to {name} — waiting for review", es: "Enviado a {name}; esperando revisión" },
  "learn.state.changes_requested": { en: "{name} asked for changes", es: "{name} pidió cambios" },
  "learn.state.approved": { en: "Approved by a supervisor or owner for the Hex-Portal archive", es: "Aprobado por un supervisor o dueño para el archivo de Hex-Portal" },
  "learn.state.withdrawn": { en: "Withdrawn from Hex-Portal", es: "Retirado de Hex-Portal" },
  "learn.state.unsaved": { en: "Not saved yet", es: "Todavía no guardado" },
  "learn.approvalMeaning": { en: "Approval archives this observation. It is not a new installation instruction and never overrides the manufacturer or safety rules.", es: "La aprobación archiva esta observación. No es una nueva instrucción de instalación y nunca reemplaza al fabricante ni las reglas de seguridad." },
  "learn.delivery.pending": { en: "Approved — not sent to Hex-Portal yet. Not received.", es: "Aprobado; todavía no se envió a Hex-Portal. No recibido." },
  "learn.delivery.needs_link": { en: "Approved — waiting for job connection. A supervisor or owner must connect this job in Hex-Portal, then tap Retry.", es: "Aprobado; esperando la conexión de la obra. Un supervisor o dueño debe conectar esta obra en Hex-Portal y luego tocar Reintentar." },
  "learn.delivery.pilot_paused": { en: "Approved — the Hex-Portal pilot for this job is paused. Not received. Tap Retry once it is running again.", es: "Aprobado; el piloto de Hex-Portal de esta obra está en pausa. No recibido. Toca Reintentar cuando vuelva a funcionar." },
  "learn.delivery.failed": { en: "Sending to Hex-Portal did not go through ({attempts} tries). Not received. Tap Retry.", es: "El envío a Hex-Portal no se completó ({attempts} intentos). No recibido. Toca Reintentar." },
  "learn.delivery.delivered": { en: "Received by Hex-Portal for learning review {when} (receipt {receipt}). This is an archive receipt, not published guidance.", es: "Recibido por Hex-Portal para revisión de aprendizaje {when} (recibo {receipt}). Es un recibo de archivo, no una guía publicada." },
  "learn.delivery.removed_remote": { en: "Removed in Hexcore {when} (receipt {receipt}). It will not be sent again. The Forge record stays.", es: "Eliminado en Hexcore {when} (recibo {receipt}). No se enviará otra vez. El registro en Forge se conserva." },
  "learn.delivery.not_configured": { en: "The connection to Hex-Portal is not set up on the server yet. Nothing was sent.", es: "La conexión con Hex-Portal todavía no está configurada en el servidor. No se envió nada." },
  "learn.delivery.not_current": { en: "This approval is no longer current or you cannot send it. Nothing was recorded.", es: "Esta aprobación ya no está vigente o no puedes enviarla. No se registró nada." },
  "learn.retry": { en: "Retry sending", es: "Reintentar envío" },
  "learn.retryRemoval": { en: "Retry removal", es: "Reintentar retiro" },
  "learn.withdrawal.pending": { en: "Withdrawn here — removal from Hex-Portal not confirmed yet.", es: "Retirado aquí; Hex-Portal todavía no confirma que lo quitó." },
  "learn.withdrawal.failed": { en: "Withdrawn here — removal from Hex-Portal did not go through ({attempts} tries). Tap Retry removal.", es: "Retirado aquí; el retiro en Hex-Portal no se completó ({attempts} intentos). Toca Reintentar retiro." },
  "learn.withdrawal.removed": { en: "Hex-Portal confirmed removal {when} (receipt {receipt}).", es: "Hex-Portal confirmó el retiro {when} (recibo {receipt})." },
  "learn.withdrawal.reason": { en: "Withdrawn by {name}: {reason}", es: "Retirado por {name}: {reason}" },
  "learn.withdraw": { en: "Withdraw from Hex-Portal", es: "Retirar de Hex-Portal" },
  "learn.withdrawReason": { en: "Why is it being withdrawn? (required)", es: "¿Por qué se retira? (obligatorio)" },
  "learn.withdrawNote": { en: "It leaves every Hex-Portal export at once. The original Forge case, words and recording stay.", es: "Sale de toda exportación de Hex-Portal de inmediato. El caso, las palabras y la grabación originales se conservan en Forge." },
  "learn.forward": { en: "Send to a supervisor for approval", es: "Enviar a un supervisor para aprobar" },
  "learn.forwardTo": { en: "Send to {name} for approval", es: "Enviar a {name} para aprobar" },
  "learn.forwardHelp": { en: "Foremen review and pass it on; only a supervisor or owner approves it for Hex-Portal.", es: "Los capataces revisan y lo pasan; solo un supervisor o dueño lo aprueba para Hex-Portal." },
  "learn.reassign": { en: "Reassign to {name}", es: "Reasignar a {name}" },
  "learn.reassignHelp": { en: "The named reviewer cannot act. Choose another reviewer and say why.", es: "El revisor nombrado no puede actuar. Elige otro revisor y di por qué." },
  "learn.reassignReason": { en: "Reason (required)", es: "Motivo (obligatorio)" },
  "learn.reviewerNote": { en: "Reviewer's note", es: "Nota del revisor" },
  "learn.history": { en: "History", es: "Historial" },
  "learn.event.draft_saved": { en: "{actor} saved revision {revision}", es: "{actor} guardó la revisión {revision}" },
  "learn.event.submitted": { en: "{actor} sent it to {reviewer}", es: "{actor} lo envió a {reviewer}" },
  "learn.event.reassigned": { en: "{actor} sent it to {reviewer} instead", es: "{actor} lo envió a {reviewer} en su lugar" },
  "learn.event.changes_requested": { en: "{actor} asked for changes", es: "{actor} pidió cambios" },
  "learn.event.approved": { en: "{actor} approved it for the archive", es: "{actor} lo aprobó para el archivo" },
  "learn.event.forwarded": { en: "{actor} reviewed it and sent it to {reviewer} for approval", es: "{actor} lo revisó y lo envió a {reviewer} para aprobar" },
  "learn.event.withdrawn": { en: "{actor} withdrew it from Hex-Portal", es: "{actor} lo retiró de Hex-Portal" },
  "learn.event.oversight": { en: "as supervisor oversight", es: "como supervisión" },
  "learn.author": { en: "Written by {name}", es: "Escrito por {name}" },
  "learn.open": { en: "Open", es: "Abrir" },
  "learn.close": { en: "Close", es: "Cerrar" },
  "learn.edit": { en: "Make the changes", es: "Hacer los cambios" },
  "learn.writeUp": { en: "Write up the lesson", es: "Escribir la lección" },
  "learn.decisionNote": { en: "Note to the author (required to ask for changes)", es: "Nota para quien escribió (necesaria para pedir cambios)" },
  "learn.requestChanges": { en: "Ask for changes", es: "Pedir cambios" },
  "learn.approve": { en: "Approve for archive", es: "Aprobar para el archivo" },
  "learn.asOversight": { en: "Decide as supervisor oversight (recorded)", es: "Decidir como supervisión (queda registrado)" },
  "learn.notYours": { en: "Only the named reviewer decides, unless a supervisor or owner decides as oversight.", es: "Solo decide el revisor nombrado, salvo que un supervisor o dueño decida como supervisión." },
  "learn.stale": { en: "Someone changed this on another screen. The latest is shown; nothing from your tap was saved.", es: "Alguien lo cambió en otra pantalla. Se muestra lo más reciente; tu toque no guardó nada." },
  "learn.otherAccount": { en: "This belongs to another sign-in on this phone. Nothing was sent.", es: "Esto pertenece a otra sesión en este teléfono. No se envió nada." },
  "learn.unavailable": { en: "Lesson review is not available on the server yet.", es: "La revisión de lecciones todavía no está disponible en el servidor." },
  "learn.loadFailed": { en: "Could not load. Drafts saved on this phone stay in the sync queue.", es: "No se pudo cargar. Los borradores guardados en este teléfono siguen en la cola." },
  "learn.mine": { en: "My lesson write-ups", es: "Mis lecciones" },
  "learn.assigned": { en: "Sent to me for review", es: "Enviadas a mí para revisar" },
  "learn.oversight": { en: "All sent write-ups (oversight)", es: "Todas las lecciones enviadas (supervisión)" },
  "learn.empty": { en: "Nothing here yet.", es: "Todavía no hay nada." },
  "learn.refresh": { en: "Refresh", es: "Actualizar" },
  "learn.fromAsk": { en: "Ask prepared this from what you said. Check every heading; nothing is saved or sent until you tap.", es: "Ask lo preparó con lo que dijiste. Revisa cada punto; no se guarda ni se envía nada hasta que toques." },
  "learn.privacy": { en: "Keep payroll, private matters and customer personal details out of lessons.", es: "No incluyas nómina, asuntos privados ni datos personales de clientes." },
} as const satisfies Record<string, CatalogEntry>;
export type LearningKey = keyof typeof LEARNING_CATALOG;
export type LearningT = (key: LearningKey, vars?: TVars) => string;
export function useLearningT(): LearningT {
  const { lang } = useLanguage();
  return useCallback((key: LearningKey, vars?: TVars) => translate(LEARNING_CATALOG, lang, key, vars), [lang]);
}
