import { useLanguage } from "../i18n";
const phrases = {
  openingMic: ["Opening microphone…", "Abriendo micrófono…"],
  keepAudioOnly: ["Keep audio without transcription", "Conservar audio sin transcripción"],
  workingMedia: ["Saving or loading evidence…", "Guardando o cargando evidencia…"],
  savingMemo: ["Saving your recording and preparing the transcript…", "Guardando tu grabación y preparando la transcripción…"],
  listenMemo: ["Listen to your memo", "Escuchar tu nota"],
  saveAudio: ["Save audio", "Guardar audio"],
  recordVideo: ["Record explanation video", "Grabar video explicativo"],
  evidenceKind: ["Evidence type", "Tipo de evidencia"],
  serviceUnit: ["Service this unit", "Dar servicio a esta unidad"],
  recovery: ["Download unsynced changes", "Descargar cambios sin sincronizar"],
  clearSaved: [
    "Clear these saved requests",
    "Quitar estas solicitudes guardadas",
  ],
  clearConfirm: [
    "Clear the saved requests from this device? Download a recovery copy first. Payroll records will not change.",
    "¿Quitar las solicitudes de este dispositivo? Descargue primero una copia. No cambiarán los registros de nómina.",
  ],
  title: ["Servicing", "Servicio técnico"],
  intro: [
    "Repair a unit, record the evidence, and keep every return visit.",
    "Repare una unidad, registre evidencia y conserve cada visita.",
  ],
  current: ["Current visit", "Visita actual"],
  records: ["Service records", "Historial de servicio"],
  legacy: ["Earlier service cases", "Casos anteriores"],
  newVisit: ["Start a service visit", "Iniciar visita de servicio"],
  job: ["Job", "Proyecto"],
  chooseJob: ["Choose a job", "Elija un proyecto"],
  allJobs: ["All jobs", "Todos los proyectos"],
  search: ["Search jobs…", "Buscar proyectos…"],
  active: ["Active", "Activo"],
  completed: ["Completed", "Completado"],
  returnVisit: ["New return visit", "Nueva visita de seguimiento"],
  open: ["Open visit", "Abrir visita"],
  back: ["Back to visits", "Volver a las visitas"],
  units: ["Units on this visit", "Unidades de esta visita"],
  addUnit: ["Add a unit", "Agregar unidad"],
  chooseUnit: ["Saved unit or custom", "Unidad guardada o personalizada"],
  custom: ["Custom unit", "Unidad personalizada"],
  unitLabel: ["Unit number / name", "Número / nombre de unidad"],
  type: ["Window / door type", "Tipo de ventana / puerta"],
  material: ["Frame material", "Material del marco"],
  story: ["Floor / story", "Piso"],
  location: ["Building / room / location", "Edificio / habitación / ubicación"],
  width: ["Width (inches)", "Ancho (pulgadas)"],
  height: ["Height (inches)", "Alto (pulgadas)"],
  unknown: ["Unknown", "Desconocido"],
  vinyl: ["Vinyl", "Vinilo"],
  aluminum: ["Aluminum", "Aluminio"],
  other: ["Other", "Otro"],
  issue: [
    "Reported issue / what did you find?",
    "Problema reportado / ¿qué encontró?",
  ],
  save: ["Save", "Guardar"],
  saveStart: ["Save and start this unit", "Guardar e iniciar esta unidad"],
  cancel: ["Cancel", "Cancelar"],
  edit: ["Edit unit report", "Editar reporte de unidad"],
  start: ["Start unit", "Iniciar unidad"],
  stop: ["Stop service timer", "Detener cronómetro"],
  idle: ["Idle time", "Tiempo indirecto"],
  travel: ["Travel", "Traslado"],
  stage: ["Work stage", "Etapa del trabajo"],
  activity: ["What are you doing?", "¿Qué está haciendo?"],
  timer: ["Current activity", "Actividad actual"],
  clockJob: [
    "Clock into this service job",
    "Registrar entrada a este proyecto",
  ],
  clockHelp: [
    "Your job clock supplies payroll hours. Service timers describe how those hours were spent.",
    "El reloj del proyecto registra las horas de nómina. Los cronómetros de servicio describen cómo se usaron.",
  ],
  clockManage: ["Job clock / break", "Reloj del proyecto / descanso"],
  clockSwitch: [
    "Finish or switch your current job clock before servicing this job.",
    "Termine o cambie su reloj actual antes de trabajar en este proyecto.",
  ],
  clockSafety: [
    "Complete today’s toolbox talk before clocking in.",
    "Complete la charla de seguridad de hoy antes de registrar entrada.",
  ],
  crewTravel: ["Crew, truck & travel", "Equipo, vehículo y traslado"],
  crewNames: ["People servicing with you", "Personas que le acompañan"],
  crewHelp: [
    "Names are notes. Each worker starts their own timer to record their hours.",
    "Los nombres son notas. Cada trabajador inicia su propio cronómetro para registrar sus horas.",
  ],
  truck: ["Truck / vehicle", "Camioneta / vehículo"],
  estimatedMiles: ["Estimated one-way miles", "Millas estimadas de ida"],
  actualMiles: ["Actual round-trip miles", "Millas reales de ida y vuelta"],
  lodging: ["Lodging required", "Requiere hospedaje"],
  date: ["Service date", "Fecha de servicio"],
  tripNotes: ["Travel / lodging notes", "Notas de traslado / hospedaje"],
  lodgingCost: ["Lodging cost ($)", "Costo de hospedaje ($)"],
  partsCost: ["Parts cost ($)", "Costo de piezas ($)"],
  otherCost: ["Other trip expenses ($)", "Otros gastos del viaje ($)"],
  supervisor: ["Job supervisor", "Supervisor del proyecto"],
  allSupervisors: [
    "All supervisors (none assigned)",
    "Todos los supervisores (sin asignar)",
  ],
  notifySent: [
    "Lodging request saved in the job chat.",
    "Solicitud de hospedaje guardada en el chat del proyecto.",
  ],
  notifyPending: [
    "Lodging notification is pending. Assign an active supervisor, then retry.",
    "Notificación de hospedaje pendiente. Asigne un supervisor activo y reintente.",
  ],
  retry: ["Retry sync", "Reintentar sincronización"],
  failPoint: ["Fail point", "Punto de falla"],
  cause: ["Reported responsibility", "Responsabilidad reportada"],
  pending: ["Diagnosis pending", "Diagnóstico pendiente"],
  manufacturer: ["Manufacturer error", "Error del fabricante"],
  customer: ["Customer damage", "Daño del cliente"],
  installer: ["Installation error / damage", "Error / daño de instalación"],
  billManufacturer: ["Strata pays", "Paga Strata"],
  billCustomer: [
    "Forge bills STG; STG bills the customer",
    "Forge factura a STG; STG factura al cliente",
  ],
  billInstaller: ["Forge absorbs the cost", "Forge absorbe el costo"],
  repair: ["Repair / parts used", "Reparación / piezas utilizadas"],
  verification: ["How did you test the result?", "¿Cómo probó el resultado?"],
  prevention: [
    "What did you learn / how can this be prevented?",
    "¿Qué aprendió / cómo se puede prevenir?",
  ],
  nextSteps: [
    "Next steps / parts / return visit",
    "Próximos pasos / piezas / próxima visita",
  ],
  outcome: ["Result", "Resultado"],
  resolved: ["Resolved", "Resuelto"],
  temporary: ["Temporary repair", "Reparación temporal"],
  return_needed: [
    "Return visit / parts needed",
    "Requiere otra visita / piezas",
  ],
  unresolved: ["Still being diagnosed", "Diagnóstico en proceso"],
  memo: ["Guided service memo", "Nota de voz guiada"],
  memoHelp: [
    "Record up to 3 minutes. Stop to save the audio and transcribe automatically. Review the words before adding them to the unit report.",
    "Graba hasta 3 minutos. Al detener, se guarda el audio y se transcribe automáticamente. Revisa las palabras antes de agregarlas al reporte.",
  ],
  record: ["Record voice memo", "Grabar nota de voz"],
  stopRecord: ["Stop recording", "Detener grabación"],
  transcribe: ["Transcribe saved memo", "Transcribir nota guardada"],
  transcribing: ["Transcribing…", "Transcribiendo…"],
  transcript: ["Memo / confirmed explanation", "Nota / explicación confirmada"],
  useTranscript: [
    "Add transcript to explanation",
    "Agregar transcripción a la explicación",
  ],
  evidence: ["Photos, video & receipts", "Fotos, video y recibos"],
  before: ["Before photo", "Foto antes"],
  after: ["After photo", "Foto después"],
  photo: ["Supporting photo", "Foto de apoyo"],
  voice: ["Voice memo", "Nota de voz"],
  video: ["Explanation video", "Video explicativo"],
  receipt: ["Receipt", "Recibo"],
  upload: ["Attach file", "Adjuntar archivo"],
  evidenceException: [
    "Missing evidence — explain for supervisor review",
    "Evidencia faltante — explique para revisión",
  ],
  evidenceHelp: [
    "Show the whole unit, the fail point, and the finished result. Keep the explanation short.",
    "Muestre la unidad, el punto de falla y el resultado final. Explique brevemente.",
  ],
  savedFiles: ["Saved evidence", "Evidencia guardada"],
  pendingFiles: ["Files waiting to upload", "Archivos pendientes"],
  queued: [
    "Saved on this device; waiting to sync",
    "Guardado en este dispositivo; pendiente de sincronizar",
  ],
  queueConflict: [
    "A saved change needs review. Keep this device and retry after checking the visit.",
    "Un cambio guardado requiere revisión. Conserve este dispositivo y reintente tras revisar la visita.",
  ],
  sync: ["Refresh / sync", "Actualizar / sincronizar"],
  loading: ["Loading service records…", "Cargando registros…"],
  unavailable: [
    "Servicing is waiting for its database update. Your job clock remains available.",
    "Servicio técnico espera su actualización. El reloj del proyecto sigue disponible.",
  ],
  finish: ["Finish visit", "Terminar visita"],
  finishHelp: [
    "Each worker stops their own service timer. Finishing the visit does not clock anyone out of payroll.",
    "Cada trabajador detiene su cronómetro. Terminar la visita no registra salida de nómina.",
  ],
  reportPending: ["Report needs attention", "El reporte requiere atención"],
  reportReady: ["Report ready to export", "Reporte listo para exportar"],
  billingPending: [
    "Pending supervisor billing review",
    "Pendiente de revisión de facturación",
  ],
  billingApproved: [
    "Billing responsibility reviewed",
    "Responsabilidad de facturación revisada",
  ],
  review: [
    "Review billing & shared costs",
    "Revisar facturación y costos compartidos",
  ],
  reviewHelp: [
    "Each unit’s labor follows its reported responsibility. Split shared travel, idle time, mileage and expenses once for the visit.",
    "Las horas de cada unidad siguen su responsabilidad. Distribuya traslado, tiempo indirecto, millas y gastos una sola vez.",
  ],
  manufacturerPct: ["Strata share (%)", "Porcentaje de Strata (%)"],
  customerPct: ["STG / customer share (%)", "Porcentaje de STG / cliente (%)"],
  installerPct: ["Forge share (%)", "Porcentaje de Forge (%)"],
  allocationReason: [
    "Explain the shared-cost split",
    "Explique la distribución de costos",
  ],
  approve: ["Approve billing review", "Aprobar revisión de facturación"],
  exportPdf: ["Download service PDF", "Descargar PDF de servicio"],
  exportCsv: ["Export service hours", "Exportar horas de servicio"],
  exportPacket: [
    "Download report & evidence ZIP",
    "Descargar reporte y evidencia ZIP",
  ],
  exportSelected: ["Export selected visits", "Exportar visitas seleccionadas"],
  select: ["Select visit", "Seleccionar visita"],
  hours: ["Recorded service hours", "Horas de servicio registradas"],
  shared: [
    "Shared travel / idle time",
    "Traslado / tiempo indirecto compartido",
  ],
  person: ["Person", "Persona"],
  dateRange: ["Date range", "Rango de fechas"],
  from: ["From", "Desde"],
  through: ["Through", "Hasta"],
  allDates: ["All dates", "Todas las fechas"],
  nothing: ["No service visits yet.", "Todavía no hay visitas."],
  noUnits: [
    "Add the first unit to begin.",
    "Agregue la primera unidad para comenzar.",
  ],
  viewJob: ["Open job", "Abrir proyecto"],
  map: ["Open job map", "Abrir mapa del proyecto"],
  timeReview: [
    "Time needs review after a payroll change.",
    "Las horas requieren revisión tras un cambio de nómina.",
  ],
  reviewTime: ["Review time record", "Revisar registro de horas"],
  startTime: ["Start", "Inicio"],
  endTime: ["End", "Fin"],
  reviewReason: ["Reason for time correction", "Motivo de corrección de horas"],
  recordingError: [
    "Microphone unavailable. Attach an audio file or type the explanation.",
    "Micrófono no disponible. Adjunte audio o escriba la explicación.",
  ],
  offlineNew: [
    "Connect before creating a new visit. Existing notes and evidence can be saved on this device.",
    "Conéctese para crear una visita. Las notas y evidencia existentes se guardan en este dispositivo.",
  ],
  noExport: [
    "Finish the report and resolve the checklist before exporting.",
    "Complete el reporte y resuelva la lista antes de exportar.",
  ],
  gap_visit: ["Finish the visit", "Termine la visita"],
  gap_running: [
    "Stop running service timers",
    "Detenga los cronómetros activos",
  ],
  gap_time: ["Review flagged labor records", "Revise las horas marcadas"],
  gap_units: ["Add a serviced unit", "Agregue una unidad"],
  gap_details: [
    "Complete each unit’s diagnosis, responsibility, repair, test and memo",
    "Complete diagnóstico, responsabilidad, reparación, prueba y nota de cada unidad",
  ],
  gap_evidence: [
    "Attach before/after photos, voice and video, or explain missing evidence",
    "Adjunte fotos antes/después, audio y video, o explique la evidencia faltante",
  ],
  prompt1: [
    "Confirm the job, unit, product, material and location.",
    "Confirme proyecto, unidad, producto, material y ubicación.",
  ],
  prompt2: [
    "What did the customer report, and what did you observe?",
    "¿Qué reportó el cliente y qué observó usted?",
  ],
  prompt3: [
    "Where did it fail? Who is responsible, and what supports that?",
    "¿Dónde falló? ¿Quién es responsable y qué evidencia lo apoya?",
  ],
  prompt4: [
    "What did you repair or replace? How did you test the result?",
    "¿Qué reparó o reemplazó? ¿Cómo probó el resultado?",
  ],
  prompt5: [
    "Who helped? Explain delays and confirm the recorded time.",
    "¿Quién ayudó? Explique demoras y confirme el tiempo registrado.",
  ],
  prompt6: [
    "What did you learn, and what happens next?",
    "¿Qué aprendió y cuáles son los próximos pasos?",
  ],
} as const;
export type ServiceText = keyof typeof phrases;
export function useServiceText() {
  const { lang } = useLanguage();
  return (key: ServiceText) => phrases[key][lang === "es" ? 1 : 0];
}

const stageSpanish: Record<string, string> = {
  Diagnosis: "Diagnóstico",
  Preparation: "Preparación",
  Flashing: "Impermeabilización",
  "Setting frame": "Colocación de marco",
  Glazing: "Colocación de vidrio",
  Hardware: "Herrajes",
  "Repair / replacement": "Reparación / reemplazo",
  Testing: "Pruebas",
  "Detail work": "Detalles",
  "Idle time": "Tiempo indirecto",
  Travel: "Traslado",
};
export function useServiceStage() {
  const { lang } = useLanguage();
  return (value: string) =>
    lang === "es" ? (stageSpanish[value] ?? value) : value;
}
