// Ask-only copy loads with the lazy Ask page instead of the morning app shell.
import { useCallback } from "react";
import { useLanguage } from "../../lib/i18n/context";
import type { TKey as AppKey } from "../../lib/i18n/catalog";
import { translate, type CatalogEntry, type TVars } from "../../lib/i18n/translate";

export const FIELD_CATALOG = {
  "field.suggestUnits": { en: "What units are on my job?", es: "¿Qué unidades hay en mi obra?" },
  "field.suggestNewJob": { en: "Start a new project", es: "Empezar un proyecto nuevo" },
  "field.checklist": { en: "Setup checklist", es: "Lista de datos" },
  "field.checklistHelp": { en: "Answer several at once, by voice or text. Unknown stays unknown.", es: "Responde varias a la vez, por voz o texto. Lo desconocido queda como desconocido." },
  "field.status.captured": { en: "Answered", es: "Respondido" },
  "field.status.unknown": { en: "Said unknown", es: "Dijo que no sabe" },
  "field.status.missing": { en: "Still needed", es: "Falta" },
  "field.status.not_applicable": { en: "Not needed", es: "No aplica" },
  "field.fromPlans": { en: "from plans", es: "de los planos" },
  "field.beforeTiming": { en: "needed before timing", es: "necesario para el temporizador" },
  "field.key.job_name": { en: "Job name", es: "Nombre de la obra" },
  "field.key.job_location": { en: "Site location", es: "Ubicación" },
  "field.key.label": { en: "Unit number or name", es: "Número o nombre de la unidad" },
  "field.key.type_label": { en: "Unit type", es: "Tipo de unidad" },
  "field.key.components": { en: "Components and quantities", es: "Componentes y cantidades" },
  "field.key.material": { en: "Frame material", es: "Material del marco" },
  "field.key.width_in": { en: "Width (in)", es: "Ancho (pulg.)" },
  "field.key.height_in": { en: "Height (in)", es: "Alto (pulg.)" },
  "field.key.area_source": { en: "Size measured, from plans, or estimated", es: "Medida en sitio, de planos o estimada" },
  "field.key.story": { en: "Story / floor", es: "Piso" },
  "field.key.opening_direction": { en: "Opening direction (outside looking in)", es: "Dirección de apertura (desde afuera)" },
  "field.key.electrical": { en: "Electrical components", es: "Componentes eléctricos" },
  "field.key.access": { en: "Access", es: "Acceso" },
  "field.key.complexity": { en: "Complexity", es: "Complejidad" },
  "field.key.equipment_needed": { en: "Machinery needed", es: "Maquinaria necesaria" },
  "field.reason.similar_job": { en: "A similar job already exists. Do you still want to create this project?", es: "Ya existe una obra parecida. ¿Todavía quieres crear este proyecto?" },
  "field.reason.fact_conflict": { en: "Unit {label} already has different details. Keep what is saved, or correct the record?", es: "La unidad {label} ya tiene otros datos. ¿Conservar lo guardado o corregir el registro?" },
  "field.reason.plan_conflict": { en: "The plans say something different for this unit. Which should the field record use?", es: "Los planos dicen algo distinto para esta unidad. ¿Qué debe usar el registro de campo?" },
  "field.reason.identity": { en: "The unit you named does not match the selected record ({label}). Which is it?", es: "La unidad que nombraste no coincide con el registro elegido ({label}). ¿Cuál es?" },
  "field.reason.claimed": { en: "Unit {label} is assigned to or being worked by someone else. Join as a helper with your own time?", es: "La unidad {label} está asignada o la trabaja otra persona. ¿Unirte como ayudante con tu propio tiempo?" },
  "field.reason.needs_clock": { en: "You are not clocked in. Use the job clock to clock in, then tap Start now.", es: "No has marcado entrada. Usa el reloj de trabajo y luego toca Empezar ahora." },
  "field.reason.wrong_job": { en: "Your job clock is on {job}. Switch jobs with the job clock, then tap Start now. Your time so far stays on {job}.", es: "Tu reloj está en {job}. Cambia de obra con el reloj de trabajo y luego toca Empezar ahora. Tu tiempo hasta ahora queda en {job}." },
  "field.reason.on_break": { en: "End your break and start?", es: "¿Terminar tu descanso y empezar?" },
  "field.reason.confirm_time": { en: "This phone's clock does not match the server, so the time you sent this cannot be used. Start now instead?", es: "El reloj de este teléfono no coincide con el servidor, así que no se puede usar la hora de envío. ¿Empezar ahora?" },
  "field.option.create_new": { en: "Create a separate new job", es: "Crear una obra nueva aparte" },
  "field.option.use_existing": { en: "Use {name}", es: "Usar {name}" },
  "field.option.keep_original": { en: "Keep the saved details (I misspoke)", es: "Conservar lo guardado (me equivoqué)" },
  "field.option.correct_record": { en: "Correct the unit record", es: "Corregir el registro de la unidad" },
  "field.option.send_for_review": { en: "Keep saved details; send my observation for review", es: "Conservar lo guardado y enviar mi observación a revisión" },
  "field.option.use_plans": { en: "Use the plans", es: "Usar los planos" },
  "field.option.use_said": { en: "Use what I said (plans stay unchanged)", es: "Usar lo que dije (los planos no cambian)" },
  "field.option.join_helper": { en: "Join as a helper", es: "Unirme como ayudante" },
  "field.option.start_now": { en: "Start now", es: "Empezar ahora" },
  "field.option.end_break_and_start": { en: "End break and start", es: "Terminar descanso y empezar" },
  "field.option.cancel": { en: "Cancel", es: "Cancelar" },
  "field.choiceNeeded": { en: "Your choice is needed — nothing has changed yet", es: "Se necesita tu decisión; todavía no cambió nada" },
  "field.openClock": { en: "Open job clock", es: "Abrir reloj de trabajo" },
  "field.choiceFailed": { en: "That choice was not saved. Nothing changed from it; try again.", es: "Esa decisión no se guardó. No cambió nada; intenta de nuevo." },
  "field.receipt.created": { en: "Job created: {name}. Supervisors were mentioned in its job chat ({count}).", es: "Obra creada: {name}. Se mencionó a supervisores en su chat ({count})." },
  "field.receipt.used_existing": { en: "Using the existing job {name}.", es: "Se usa la obra existente {name}." },
  "field.receipt.created_unit": { en: "Unit {label} saved.", es: "Unidad {label} guardada." },
  "field.receipt.created_from_map": { en: "Unit {label} saved on its map unit.", es: "Unidad {label} guardada en su unidad del mapa." },
  "field.receipt.details_added": { en: "Details added to unit {label}.", es: "Datos agregados a la unidad {label}." },
  "field.receipt.corrected": { en: "Unit {label} corrected. The earlier values are kept in its history.", es: "Unidad {label} corregida. Los valores anteriores quedan en su historial." },
  "field.receipt.unchanged": { en: "Unit {label} already had these details.", es: "La unidad {label} ya tenía estos datos." },
  "field.receipt.sent_for_review": { en: "Saved for a foreman to review. Unit {label} is unchanged.", es: "Guardado para revisión de un capataz. La unidad {label} no cambió." },
  "field.receipt.started": { en: "Timer running on {label} since {time}.", es: "Temporizador en {label} desde las {time}." },
  "field.receipt.already_running": { en: "Already running on {label} since {time}. Not restarted.", es: "Ya corre en {label} desde las {time}. No se reinició." },
  "field.receipt.stopped": { en: "Your timer stopped ({outcome}). Your job clock is still running. QC is not approved here.", es: "Tu temporizador se detuvo ({outcome}). Tu reloj de trabajo sigue. Aquí no se aprueba calidad." },
  "field.receipt.already_stopped": { en: "No timer was running.", es: "No había temporizador corriendo." },
  "field.receipt.released": { en: "Unit {label} released.", es: "Unidad {label} liberada." },
  "field.receipt.not_assigned": { en: "Unit {label} was not assigned to anyone.", es: "La unidad {label} no estaba asignada." },
  "field.receipt.crew_recorded": { en: "Crew record filed for {label} ({people}). No payroll hours added.", es: "Registro del equipo para {label} ({people}). No se agregaron horas de nómina." },
  "field.receipt.stale": { en: "Nothing changed.", es: "No cambió nada." },
  "field.receipt.cancelled": { en: "Cancelled. Nothing changed.", es: "Cancelado. No cambió nada." },
  "field.basis.request_sent": { en: "Started at the moment you sent the request.", es: "Empezó en el momento en que enviaste la solicitud." },
  "field.basis.tapped_start": { en: "Started when you tapped.", es: "Empezó cuando tocaste." },
  "field.helpers": { en: "{count} helper(s) still working.", es: "{count} ayudante(s) siguen trabajando." },
  "field.record": { en: "Record a voice message", es: "Grabar un mensaje de voz" },
  "field.stopRecording": { en: "Stop and send ({seconds}s)", es: "Detener y enviar ({seconds}s)" },
  "field.savingMemo": { en: "Saving your recording…", es: "Guardando tu grabación…" },
  "field.transcribing": { en: "Writing out what you said…", es: "Escribiendo lo que dijiste…" },
  "field.memo": { en: "Your recording", es: "Tu grabación" },
  "field.unsentTitle": { en: "Not sent yet — kept on this phone", es: "Aún no enviado; guardado en este teléfono" },
  "field.unsentHelp": { en: "Sending later keeps the original time. A late message never starts or stops a timer.", es: "Al enviarlo después se conserva la hora original. Un mensaje tardío nunca inicia ni detiene un temporizador." },
  "field.sendNow": { en: "Send now", es: "Enviar ahora" },
  "field.discard": { en: "Discard", es: "Descartar" },
  "field.needsConnection": { en: "Forge AI needs a connection for job and unit work. Your message is kept here. Manual clock and Current Work still work.", es: "Forge AI necesita conexión para obras y unidades. Tu mensaje queda guardado aquí. El reloj manual y Trabajo actual siguen funcionando." },
  "field.newSetup": { en: "Start a new setup", es: "Empezar otra configuración" },
  "field.restoreFailed": { en: "Earlier messages could not be loaded. New messages still work.", es: "No se pudieron cargar los mensajes anteriores. Los nuevos siguen funcionando." },
  "field.proposedJob": { en: "New job you asked for:", es: "Obra nueva que pediste:" },
  "field.timingPending": { en: "This phone still has a clock or timer change waiting to send. Nothing was started. Let it sync, then tap again.", es: "Este teléfono todavía tiene un cambio de reloj o temporizador por enviar. No se inició nada. Deja que se sincronice y vuelve a tocar." },
  "field.otherAccount": { en: "This was recorded under another sign-in on this phone. It stays with that person and was not sent.", es: "Esto se grabó con otra sesión en este teléfono. Queda con esa persona y no se envió." },
  "field.notKept": { en: "This phone could not keep your message, so it is back in the box. Send it again when you have signal.", es: "Este teléfono no pudo guardar tu mensaje; volvió al cuadro. Envíalo otra vez cuando tengas señal." },
  "field.recordingNotKept": { en: "Your recording is NOT saved yet — this phone could not keep it and it has not reached the server. Keep this screen open and tap Send now, or download it.", es: "Tu grabación TODAVÍA NO está guardada: el teléfono no pudo conservarla y no llegó al servidor. Deja esta pantalla abierta y toca Enviar ahora, o descárgala." },
  "field.downloadRecording": { en: "Download recording", es: "Descargar grabación" },
  "field.stepFailed": { en: "Some steps may not have finished. Only the saved cards above were saved.", es: "Algunos pasos pueden no haber terminado. Solo se guardó lo que aparece arriba." },
  // Daily log through Ask (K2.7).
  "field.dailyNotRecorded": { en: "Those words were NOT added to your daily log draft — no saved message is behind them. Send them again.", es: "Esas palabras NO se agregaron a tu borrador del registro; no hay un mensaje guardado detrás. Envíalas otra vez." },
  "field.dailyHide": { en: "Hide the daily log (your draft is kept)", es: "Ocultar el registro (tu borrador se conserva)" },
  // Receipts (K2.5): three words, from the receipt's status, never from prose.
  "field.receiptStatus.saved_in_forge": { en: "Saved in Forge", es: "Guardado en Forge" },
  "field.receiptStatus.needs_choice": { en: "Needs your choice", es: "Necesita tu decisión" },
  "field.receiptStatus.nothing_changed": { en: "Nothing changed", es: "No cambió nada" },
  "field.checklistKept": { en: "Kept for this conversation — nothing saved to the job yet", es: "Guardado para esta conversación; todavía nada en la obra" },
  "field.nothingSaved": { en: "Nothing was saved yet", es: "Todavía no se guardó nada" },
  "field.nothingSavedHelp": { en: "Only a receipt card under a reply proves a change.", es: "Solo una tarjeta de recibo debajo de una respuesta demuestra un cambio." },
  // One-tap clock buttons (K2.4). The AI offers; only the tap changes the clock.
  "field.button.title": { en: "Job clock", es: "Reloj de trabajo" },
  // Shown while the clock is still being read, instead of any claim about it.
  "field.button.checking": { en: "Checking your clock…", es: "Revisando tu reloj…" },
  "field.button.start_break": { en: "Start break", es: "Empezar descanso" },
  "field.button.start_lunch": { en: "Start lunch break", es: "Empezar descanso de comida" },
  "field.button.start_rest": { en: "Start rest break", es: "Empezar descanso corto" },
  "field.button.end_break": { en: "End break", es: "Terminar descanso" },
  "field.button.clock_in": { en: "Open job clock to clock in", es: "Abrir el reloj para marcar entrada" },
  "field.button.clock_out": { en: "Open job clock to clock out", es: "Abrir el reloj para marcar salida" },
  "field.button.openedClock": { en: "The job clock is open. It asks its usual questions there.", es: "El reloj de trabajo está abierto. Ahí hace sus preguntas de siempre." },
  "field.button.done.start_break.saved": { en: "On break — saved in Forge.", es: "En descanso; guardado en Forge." },
  "field.button.done.start_break.queued": { en: "On break — saved on this phone, sending when there is signal.", es: "En descanso; guardado en este teléfono, se envía cuando haya señal." },
  "field.button.done.end_break.saved": { en: "Back on the clock — saved in Forge.", es: "De vuelta al trabajo; guardado en Forge." },
  "field.button.done.end_break.queued": { en: "Back on the clock — saved on this phone, sending when there is signal.", es: "De vuelta al trabajo; guardado en este teléfono, se envía cuando haya señal." },
  "field.button.refused.not_clocked_in": { en: "You're not clocked in, so there is no break to take. Nothing changed.", es: "No has marcado entrada, así que no hay descanso que tomar. No cambió nada." },
  "field.button.refused.already_on_break": { en: "You're already on break. Nothing changed.", es: "Ya estás en descanso. No cambió nada." },
  "field.button.refused.not_on_break": { en: "You're not on break. Nothing changed.", es: "No estás en descanso. No cambió nada." },
  "field.button.refused.failed": { en: "That didn't go through. Nothing changed. Use the job clock.", es: "No se pudo. No cambió nada. Usa el reloj de trabajo." },
  // The direct try died on the network (so it may have been saved) and the
  // phone could not keep the punch to send again: neither "saved" nor
  // "nothing changed" is known to be true.
  "field.button.refused.unconfirmed": { en: "We couldn't tell whether that reached Forge, and this phone couldn't save it to send again. Open the job clock to check before you tap again.", es: "No pudimos saber si llegó a Forge, y este teléfono no pudo guardarlo para enviarlo otra vez. Abre el reloj de trabajo para revisar antes de volver a tocar." },
  // The context tag (K2.3).
  "field.tag.title": { en: "Asking about", es: "Preguntando sobre" },
  "field.tag.clear": { en: "Clear the job tag", es: "Quitar la etiqueta de obra" },
  "field.tag.unit": { en: "Unit {unit}", es: "Unidad {unit}" },
  "field.tag.job": { en: "this job", es: "esta obra" },
  // Action cards (K2.2) and All actions (K2.1).
  "field.cards.title": { en: "Actions", es: "Acciones" },
  "field.cards.all": { en: "All actions", es: "Todas las acciones" },
  "field.cards.reopen": { en: "Actions", es: "Acciones" },
  "field.cards.close": { en: "Close", es: "Cerrar" },
  "field.cards.notYet": { en: "not in Ask yet (release {release})", es: "todavía no está en Ask (versión {release})" },
  "field.cards.useScreen": { en: "Use the {screen} screen for this", es: "Usa la pantalla {screen} para esto" },
  "field.cards.asks": { en: "Asks: {list}", es: "Pregunta: {list}" },
  "field.cards.never": { en: "Forge AI never:", es: "Forge AI nunca:" },
  "field.cards.questions": { en: "Quick questions", es: "Preguntas rápidas" },
  "field.cards.receipt.saved_in_forge": { en: "Receipt: Saved in Forge", es: "Recibo: Guardado en Forge" },
  "field.cards.receipt.saved_on_phone": { en: "Receipt: Saved on this phone until you tap Save, then Saved in Forge", es: "Recibo: Guardado en este teléfono hasta que toques Guardar, y después Guardado en Forge" },
  "field.cards.receipt.needs_choice": { en: "Receipt: Needs your choice, then Saved in Forge", es: "Recibo: Necesita tu decisión, y después Guardado en Forge" },
  "field.cards.receipt.read_only": { en: "Shows a card. Nothing changes.", es: "Muestra una tarjeta. No cambia nada." },
  "field.cards.receipt.one_tap_button": { en: "Shows a button. Only your tap changes the clock.", es: "Muestra un botón. Solo tu toque cambia el reloj." },
} as const satisfies Record<string, CatalogEntry>;
export type FieldKey = keyof typeof FIELD_CATALOG;
export type TKey = AppKey | FieldKey;
export type TFn = (key: TKey, vars?: TVars) => string;
export function useFieldT(): TFn {
  const { lang, t } = useLanguage();
  return useCallback((key: TKey, vars?: TVars) => key.startsWith("field.")
    ? translate(FIELD_CATALOG, lang, key, vars)
    : t(key as AppKey, vars), [lang, t]);
}
