// QC overlay for new-design-qc-continuity.spec.ts (saved-record continuity,
// 2026-10-06).
//
// Built on the UNCHANGED base designContinuityFixtures.ts (openContinuityPage,
// role owner), NOT on designRecordContinuityFixtures.ts: that file's
// FORBIDDEN_MUTATIONS deliberately lists record_qc_decision, and loosening it
// would weaken the photo and crew specs. Everything here is registered AFTER
// the base install, so it wins only for the exact routes it names; every other
// REST write still meets the base refusal screen (base.log.unexpectedWrites).
//
//   - POST rpc/record_qc_decision: the simulated server. The decision id is
//     generated by the APP (Qc.tsx decisionIdFor, crypto.randomUUID) and sent
//     as p_decision_id; migration 20261041000000 record_qc_decision stores the
//     event under that id and returns it. So this handler stores and returns
//     the app's id — it is NOT a server-minted id, and the legacy decision has
//     no revision. Exactly one well-formed Pass is accepted; anything else is
//     logged and refused with 409. This handler is the only place the QC state
//     (one qc_decision_events row, one qc_checks row) ever changes.
//   - GET qc_checks / qc_decision_events, and the two exact project_openings
//     selects Qc.tsx's queue and history send: served from that state, cloned,
//     with only the filters those readers send modelled (eq, in, not.in on
//     named columns). Any other filter is answered 400 and logged.
//     project_openings GETs with any other select fall back to the base.
//   - GET profiles with select "id,display_name" and id=in.(TEST_USER): the
//     history's reviewer join only. Every other profiles read falls back to
//     the base, so the profile / design preference stays the base's live row.
//
// A `request` listener and a `requestfinished` listener count every POST to
// rpc/record_qc_decision attempted and completed — the browser's own ledger.
//
// Limits: one synthetic OWNER in one browser context; no SQL (dedupe,
// transaction, points), RLS, auth or PostgREST is executed; the legacy QC
// history only — not the dormant unit final-QC authority, an installed PWA or
// physical field proof. The reviewer name and project join are fixture answers.

import type { Page, Route } from "@playwright/test";
import {
  createContinuityServer,
  openContinuityPage,
  type ContinuityServer,
} from "./designContinuityFixtures";
import { TEST_USER } from "./supabaseFixtures";
import { json } from "./specHelpers";
import { OAKRIDGE } from "./release1Fixtures";

type Row = Record<string, unknown>;

/** The one installed opening the queue starts with — input, not a saved decision. */
export const QC_OPENING_ID = "99999999-3333-4999-8999-999999999999";
export const QC_OPENING_CODE = "CONTINUITY-QC-1";
/** The reviewer join answered for profiles(id, display_name). */
export const REVIEWER_NAME = "E2E Fixture";
/** Exactly the arguments lib/ops.ts setQc sends. */
export const QC_RPC_KEYS = ["p_decision_id", "p_note", "p_opening_id", "p_status"] as const;

const RPC_PATH = /\/rest\/v1\/rpc\/record_qc_decision(\?|$)/;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// postgrest-js strips whitespace from select strings before sending them.
const QUEUE_SELECT = "id,opening_code,project_id,status,assigned_window_id,window_types(type_code),qc:qc_checks(status),projects(job_code)";
const HISTORY_OPENING_SELECT = "id,opening_code,project_id,projects(job_code)";
const NOT_FILTERS = new Set(["select", "order", "limit", "offset"]);

export interface QcRead { table: string; select: string; query: string; rows: Row[] }

export interface QcContinuityServer {
  base: ContinuityServer;
  /** Installed opening rows (input). Never changed. */
  openings: Row[];
  /** qc_decision_events rows — written ONLY by the record_qc_decision handler. */
  events: Row[];
  /** qc_checks rows — written ONLY by the record_qc_decision handler. */
  checks: Row[];
  ledgers: {
    /** record_qc_decision bodies, exactly as the handler received them. */
    saves: Row[];
    /** Bodies the handler refused. Must stay empty. */
    refusedSaves: Row[];
    /** Every read this overlay served. */
    reads: QcRead[];
    /** Filters this overlay does not model — answered 400. Must stay empty. */
    unsupportedReads: string[];
    /** POSTs to rpc/record_qc_decision attempted (request listener). */
    attempted: string[];
    /** POSTs to rpc/record_qc_decision completed with any status (requestfinished). */
    completed: string[];
  };
}

export function createQcContinuityServer(): QcContinuityServer {
  // The owner starts on classic with the master switch on, and moves both only
  // through the real Settings controls; the base refuses the switch otherwise.
  const base = createContinuityServer({ uiDesign: "classic", masterOn: true });
  base.expected.add("set_new_design_switch");
  return {
    base,
    openings: [{
      id: QC_OPENING_ID, opening_code: QC_OPENING_CODE, project_id: OAKRIDGE, status: "installed",
      assigned_window_id: null, window_types: null, projects: { job_code: "OAKRIDGE" },
      work_ended_at: "2026-10-05T18:00:00.000Z",
    }],
    events: [],
    checks: [],
    ledgers: { saves: [], refusedSaves: [], reads: [], unsupportedReads: [], attempted: [], completed: [] },
  };
}

/** One PostgREST filter: eq.x, in.(a,b), optionally prefixed not. — null when not modelled. */
function matches(value: unknown, raw: string): boolean | null {
  const negate = raw.startsWith("not.");
  const filter = negate ? raw.slice(4) : raw;
  const dot = filter.indexOf(".");
  const op = filter.slice(0, dot);
  const arg = filter.slice(dot + 1);
  let hit: boolean;
  if (op === "eq") hit = String(value) === arg;
  else if (op === "in" && arg.startsWith("(") && arg.endsWith(")")) {
    hit = arg.slice(1, -1).split(",").map((x) => x.replace(/^"|"$/g, "")).includes(String(value));
  } else return null;
  return negate ? !hit : hit;
}

/** Rows passing every filter, or a 400 (logged) for a column/operator not in `columns`. */
async function filtered(route: Route, server: QcContinuityServer, table: string, rows: Row[], columns: string[]): Promise<Row[] | null> {
  const params = new URL(route.request().url()).searchParams;
  let out = rows;
  for (const key of new Set(params.keys())) {
    if (NOT_FILTERS.has(key)) continue;
    for (const raw of params.getAll(key)) {
      if (!columns.includes(key) || matches("", raw) === null) {
        server.ledgers.unsupportedReads.push(`${table}?${key}=${raw}`);
        await route.fulfill({ status: 400, contentType: "application/json", body: JSON.stringify({ message: `QC fixture does not model ${table} ${key}=${raw}` }) });
        return null;
      }
      out = out.filter((r) => matches(r[key], raw));
    }
  }
  return out;
}

function serve(route: Route, server: QcContinuityServer, table: string, rows: Row[]) {
  const url = new URL(route.request().url());
  const served = structuredClone(rows);
  server.ledgers.reads.push({ table, select: url.searchParams.get("select") ?? "", query: url.search, rows: structuredClone(served) });
  return json(route, served, served.length);
}

const isRead = (route: Route) => route.request().method() === "GET" || route.request().method() === "HEAD";
const selectOf = (route: Route) => (new URL(route.request().url()).searchParams.get("select") ?? "").replace(/\s+/g, "");

async function installQcRoutes(page: Page, server: QcContinuityServer) {
  // listQcQueue's first read: the opening ids with a passed check.
  await page.route("**/rest/v1/qc_checks**", async (route) => {
    if (!isRead(route)) return route.fallback();
    const rows = await filtered(route, server, "qc_checks", server.checks, ["status", "project_opening_id"]);
    return rows && serve(route, server, "qc_checks", rows);
  });

  // listQcHistory: newest first, limit + 1.
  await page.route("**/rest/v1/qc_decision_events**", async (route) => {
    if (!isRead(route)) return route.fallback();
    const rows = await filtered(route, server, "qc_decision_events", server.events, []);
    if (!rows) return;
    const limit = Number(new URL(route.request().url()).searchParams.get("limit") ?? rows.length);
    const sorted = [...rows].sort((a, b) =>
      String(b.decided_at).localeCompare(String(a.decided_at)) || String(b.id).localeCompare(String(a.id)));
    return serve(route, server, "qc_decision_events", sorted.slice(0, limit));
  });

  // Only the two exact selects Qc.tsx sends; every other opening read is the base's.
  await page.route("**/rest/v1/project_openings**", async (route) => {
    if (!isRead(route)) return route.fallback();
    const select = selectOf(route);
    if (select === QUEUE_SELECT) {
      const rows = await filtered(route, server, "project_openings", server.openings, ["status", "id"]);
      if (!rows) return;
      return serve(route, server, "project_openings", rows.map((o) => {
        const check = server.checks.find((c) => c.project_opening_id === o.id);
        return {
          id: o.id, opening_code: o.opening_code, project_id: o.project_id, status: o.status,
          assigned_window_id: o.assigned_window_id, window_types: o.window_types,
          qc: check ? { status: check.status } : null, projects: o.projects,
        };
      }));
    }
    if (select === HISTORY_OPENING_SELECT) {
      const rows = await filtered(route, server, "project_openings", server.openings, ["id"]);
      if (!rows) return;
      return serve(route, server, "project_openings",
        rows.map((o) => ({ id: o.id, opening_code: o.opening_code, project_id: o.project_id, projects: o.projects })));
    }
    return route.fallback();
  });

  // The history's reviewer join, and nothing else.
  await page.route("**/rest/v1/profiles**", (route) => {
    if (!isRead(route) || selectOf(route) !== "id,display_name") return route.fallback();
    if (new URL(route.request().url()).searchParams.get("id") !== `in.(${TEST_USER.id})`) return route.fallback();
    return serve(route, server, "profiles", [{ id: TEST_USER.id, display_name: REVIEWER_NAME }]);
  });

  // The one expected Pass. All QC state changes happen here, in answer to the
  // UI's own request, and nowhere else.
  await page.route((url) => RPC_PATH.test(url.href), (route) => {
    if (route.request().method() !== "POST") return route.fallback();
    let body: Row = {};
    try {
      const parsed: unknown = route.request().postDataJSON();
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) body = parsed as Row;
    } catch {
      body = {};
    }
    server.ledgers.saves.push(structuredClone(body));
    const valid = JSON.stringify(Object.keys(body).sort()) === JSON.stringify([...QC_RPC_KEYS]) &&
      typeof body.p_decision_id === "string" && UUID.test(body.p_decision_id) &&
      body.p_opening_id === QC_OPENING_ID && body.p_status === "passed" && body.p_note === null &&
      server.events.length === 0 && server.checks.length === 0;
    if (!valid) {
      server.ledgers.refusedSaves.push(structuredClone(body));
      return route.fulfill({ status: 409, contentType: "application/json",
        body: JSON.stringify({ code: "E2E03", message: "QC continuity fixture accepts exactly one well-formed Pass" }) });
    }
    const decidedAt = new Date().toISOString();
    server.events.push({
      id: body.p_decision_id, project_opening_id: QC_OPENING_ID, status: "passed", note: null,
      reviewer_id: TEST_USER.id, decided_at: decidedAt, source: "review",
    });
    server.checks.push({ project_opening_id: QC_OPENING_ID, status: "passed" });
    return json(route, body.p_decision_id, null);
  });
}

/** openContinuityPage as the synthetic owner, then the QC overlay and the browser save ledgers. */
export async function openQcContinuityPage(page: Page, server: QcContinuityServer, opts: { session: string }) {
  await openContinuityPage(page, server.base, { session: opts.session, role: "owner" });
  await installQcRoutes(page, server);
  const isSave = (method: string, url: string) => method === "POST" && RPC_PATH.test(url);
  page.on("request", (req) => {
    if (isSave(req.method(), req.url())) server.ledgers.attempted.push(new URL(req.url()).pathname);
  });
  page.on("requestfinished", (req) => {
    if (isSave(req.method(), req.url())) server.ledgers.completed.push(new URL(req.url()).pathname);
  });
}
