"""A one-page plan sheet for the automation sandbox job, built from nothing.

WHY THIS EXISTS. The project map only offers a draggable mark when the job has a
building plan set (`buildingPdf` in ProjectMap.tsx), and the Undo bar lives
inside that same view. So a test login cannot exercise dragging, undo or reset
unless the sandbox job has a real PDF behind it — and the only other PDFs on this
database are Black Desert's and Smith Residence's, which are the two things a
test account must never write.

Rather than copy a customer's drawing into a test job, this draws a deliberately
fake sheet: an outline that reads as a building, four numbered callouts where the
sandbox marks sit, and "not a real building" printed on it twice. No dependency,
no binary blob in git, and the bytes are identical on every run.
"""
from __future__ import annotations

# Letter portrait, matching what the app's renderer expects of a plan sheet.
WIDTH = 612.0
HEIGHT = 792.0

# Where the sandbox marks sit, normalised (x from the left, y from the TOP) —
# the same convention project_openings.pin_x / pin_y use. Kept here so the
# printed callouts and the app's dots land on top of each other.
MARK_PINS: list[tuple[str, float, float]] = [
    ("1", 0.24, 0.32),
    ("2", 0.56, 0.32),
    ("3", 0.24, 0.63),
    ("4", 0.72, 0.63),
]


def _circle(cx: float, cy: float, r: float) -> str:
    """A circle as four Béziers — PDF has no arc operator."""
    k = 0.5523 * r
    return (
        f"{cx - r:.2f} {cy:.2f} m "
        f"{cx - r:.2f} {cy + k:.2f} {cx - k:.2f} {cy + r:.2f} {cx:.2f} {cy + r:.2f} c "
        f"{cx + k:.2f} {cy + r:.2f} {cx + r:.2f} {cy + k:.2f} {cx + r:.2f} {cy:.2f} c "
        f"{cx + r:.2f} {cy - k:.2f} {cx + k:.2f} {cy - r:.2f} {cx:.2f} {cy - r:.2f} c "
        f"{cx - k:.2f} {cy - r:.2f} {cx - r:.2f} {cy - k:.2f} {cx - r:.2f} {cy:.2f} c "
    )


def _content() -> str:
    lines: list[str] = []

    lines.append("BT /F1 15 Tf 0.1 0.1 0.1 rg 62 726 Td "
                 "(TEST - AUTOMATION SANDBOX) Tj ET")
    lines.append("BT /F1 9.5 Tf 0.35 0.35 0.35 rg 62 710 Td "
                 "(Not a real building. Not a real job. Safe to break.) Tj ET")

    # The shell.
    lines.append("1.6 w 0.15 0.15 0.18 RG")
    lines.append("70 140 m 542 140 l 542 640 l 70 640 l h S")

    # Interior walls, so the sheet reads as a floor plan rather than a box.
    lines.append("0.9 w 0.35 0.35 0.38 RG")
    lines.append("70 420 m 330 420 l S")
    lines.append("330 140 m 330 420 l S")
    lines.append("390 420 m 390 640 l S")

    # Callouts, at the same spots the sandbox marks are pinned.
    for label, nx, ny in MARK_PINS:
        cx = nx * WIDTH
        cy = (1.0 - ny) * HEIGHT
        lines.append("0.8 w 0.20 0.20 0.24 RG")
        lines.append(_circle(cx, cy, 11.0) + "S")
        # Roughly centred: Helvetica digits are ~0.556em wide.
        dx = cx - (len(label) * 0.556 * 10.0) / 2.0
        lines.append(f"BT /F1 10 Tf 0.1 0.1 0.1 rg {dx:.2f} {cy - 3.5:.2f} Td "
                     f"({label}) Tj ET")

    lines.append("BT /F1 8 Tf 0.45 0.45 0.45 rg 62 118 Td "
                 "(Generated by scripts/lib/tiny_pdf.py for the ZZTEST sandbox job.) Tj ET")

    return "\n".join(lines)


def sandbox_plan_pdf() -> bytes:
    """A complete, single-page PDF. Uncompressed, so it stays human-readable."""
    content = _content()
    objects = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {WIDTH:.0f} {HEIGHT:.0f}] "
        "/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        f"<< /Length {len(content)} >>\nstream\n{content}\nendstream",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n{body}\nendobj\n".encode("latin-1")

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode("latin-1")
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode("latin-1")
    out += (f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            f"startxref\n{xref_at}\n%%EOF\n").encode("latin-1")
    return bytes(out)


if __name__ == "__main__":
    import sys

    sys.stdout.buffer.write(sandbox_plan_pdf())
