// GENERATED by scripts/gen-brain-snapshot.py — do not edit by hand.
//
// The real (non-provisional) window catalog, bundled so the offline brain can
// answer type questions with no signal. Provisional rows — the "Mark #1" units
// spec extraction creates — are excluded on purpose: they are not catalog
// products and they pollute search. Keys are short to keep the payload small.
import type { CatalogType } from "./types";

export const CATALOG_SNAPSHOT: CatalogType[] = [
  {
    "c": "AWN2418",
    "n": "Awning 24x18",
    "cat": "awning",
    "w": 24,
    "h": 18,
    "d": 2
  },
  {
    "c": "AWN2424",
    "n": "Awning 24x24",
    "cat": "awning",
    "w": 24,
    "h": 24,
    "d": 2
  },
  {
    "c": "AWN2430",
    "n": "Awning 24x30",
    "cat": "awning",
    "w": 24,
    "h": 30,
    "d": 2
  },
  {
    "c": "AWN3018",
    "n": "Awning 30x18",
    "cat": "awning",
    "w": 30,
    "h": 18,
    "d": 2
  },
  {
    "c": "AWN3024",
    "n": "Awning 30x24",
    "cat": "awning",
    "w": 30,
    "h": 24,
    "d": 2,
    "t": [
      "Drain side out; flash sides first, top flashing last over the flange.",
      "Level matters - an awning that is off will not seal against the frame when cranked shut.",
      "Caulk flanges left/right/top only; leave the bottom to drain.",
      "Set flange screws after leveling, pull shims, then crank through full travel.",
      "Confirm the arm hardware operates smoothly before final caulk."
    ],
    "x": [
      "An out-of-level awning leaks at the hinge side - level carefully.",
      "Confirm setout depth up front.",
      "Do not force vinyl on hot days."
    ]
  },
  {
    "c": "AWN3030",
    "n": "Awning 30x30",
    "cat": "awning",
    "w": 30,
    "h": 30,
    "d": 2
  },
  {
    "c": "AWN3618",
    "n": "Awning 36x18",
    "cat": "awning",
    "w": 36,
    "h": 18,
    "d": 2
  },
  {
    "c": "AWN3624",
    "n": "Awning 36x24",
    "cat": "awning",
    "w": 36,
    "h": 24,
    "d": 2
  },
  {
    "c": "AWN3630",
    "n": "Awning 36x30",
    "cat": "awning",
    "w": 36,
    "h": 30,
    "d": 2
  },
  {
    "c": "AWN4218",
    "n": "Awning 42x18",
    "cat": "awning",
    "w": 42,
    "h": 18,
    "d": 2
  },
  {
    "c": "AWN4224",
    "n": "Awning 42x24",
    "cat": "awning",
    "w": 42,
    "h": 24,
    "d": 2
  },
  {
    "c": "AWN4230",
    "n": "Awning 42x30",
    "cat": "awning",
    "w": 42,
    "h": 30,
    "d": 2
  },
  {
    "c": "BAY7248",
    "n": "Bay 72x48",
    "cat": "specialty",
    "w": 72,
    "h": 48,
    "d": 5,
    "t": [
      "Bay is a structural, 3-person unit - it needs support below and cable/knee bracing above per plan.",
      "Confirm the head board and support brackets are in before you hang any weight.",
      "Flash the full perimeter carefully; the roof/seat connections are the leak risk, not just the flanges.",
      "Level and center the center lite first, then bring the flankers to it.",
      "Seal the seat and roof junctions and photograph every flashing/caulk joint."
    ],
    "x": [
      "Bays fail from under-support and roof-junction leaks - never skip the bracing or seat flashing.",
      "3-person job with heavy glass - stage the lift and keep the drop zone clear.",
      "Confirm the opening framing and setout with the foreman before starting - bays are non-starters if the rough opening is wrong."
    ]
  },
  {
    "c": "BAY7260",
    "n": "Bay 72x60",
    "cat": "specialty",
    "w": 72,
    "h": 60,
    "d": 5
  },
  {
    "c": "BAY9648",
    "n": "Bay 96x48",
    "cat": "specialty",
    "w": 96,
    "h": 48,
    "d": 5
  },
  {
    "c": "BAY9660",
    "n": "Bay 96x60",
    "cat": "specialty",
    "w": 96,
    "h": 60,
    "d": 5
  },
  {
    "c": "BOW12048",
    "n": "Bow 120x48",
    "cat": "specialty",
    "w": 120,
    "h": 48,
    "d": 5
  },
  {
    "c": "BOW12060",
    "n": "Bow 120x60",
    "cat": "specialty",
    "w": 120,
    "h": 60,
    "d": 5
  },
  {
    "c": "BOW9648",
    "n": "Bow 96x48",
    "cat": "specialty",
    "w": 96,
    "h": 48,
    "d": 5
  },
  {
    "c": "BOW9660",
    "n": "Bow 96x60",
    "cat": "specialty",
    "w": 96,
    "h": 60,
    "d": 5
  },
  {
    "c": "CAS2436",
    "n": "Casement 24x36",
    "cat": "casement",
    "w": 24,
    "h": 36,
    "d": 2
  },
  {
    "c": "CAS2448",
    "n": "Casement 24x48",
    "cat": "casement",
    "w": 24,
    "h": 48,
    "d": 2
  },
  {
    "c": "CAS2460",
    "n": "Casement 24x60",
    "cat": "casement",
    "w": 24,
    "h": 60,
    "d": 3
  },
  {
    "c": "CAS2472",
    "n": "Casement 24x72",
    "cat": "casement",
    "w": 24,
    "h": 72,
    "d": 3
  },
  {
    "c": "CAS3036",
    "n": "Casement 30x36",
    "cat": "casement",
    "w": 30,
    "h": 36,
    "d": 2
  },
  {
    "c": "CAS3048",
    "n": "Casement 30x48",
    "cat": "casement",
    "w": 30,
    "h": 48,
    "d": 2,
    "t": [
      "Drain side faces OUT. Flash sides before setting, top flashing last over the flange.",
      "Level is critical on a casement - if it is out, the sash will not seal or will swing on its own.",
      "Caulk flanges left/right/top only; leave the bottom for drainage.",
      "Set screws through the flange after leveling, then pull the shims and check the sash swings clean.",
      "Test the crank through full travel before you finish caulk."
    ],
    "x": [
      "A casement that is not dead level will not latch - do not rush the level step.",
      "Confirm setout depth (stucco vs rock) up front.",
      "Watch the sash edge for scratches when unpackaging with a utility knife."
    ]
  },
  {
    "c": "CAS3050",
    "n": "Casement 30x50",
    "cat": "casement",
    "w": 30,
    "h": 50,
    "d": 2,
    "t": [
      "Pre-check RO with diagonal tape before setting the unit",
      "Stage the unit outside the opening before the lift",
      "Use impact with clutch + plastic shims on casement hinges",
      "Bring a Japanese pull saw when the RO is racked",
      "Call out pinch points on the swing path"
    ],
    "x": [
      "Upper hinge screws can cam out on casements",
      "Out-of-square RO by 3/8\" will blow the time estimate",
      "Tempered edges — watch fingers"
    ],
    "hw": [
      {
        "t": "Dry-fit and check the rough opening",
        "d": "Measure width at 3 points and height at 2; confirm the unit fits with 1/4-1/2\" shim clearance before carrying it up."
      },
      {
        "t": "Pre-drill the hinge side",
        "d": "Last installs cammed out upper hinge screws — pre-drill to avoid it."
      },
      {
        "t": "Stage the unit outside the opening",
        "d": "Set it just outside before the lift; two-person set keeps the cladding clean."
      },
      {
        "t": "Shim and level",
        "d": "Plastic shims with an impact on clutch; check square with a diagonal tape before fastening."
      },
      {
        "t": "Flash and seal",
        "d": "Flashing tape on the first pass; foam-seal clean. Watch fingers on tempered edges."
      }
    ]
  },
  {
    "c": "CAS3060",
    "n": "Casement 30x60",
    "cat": "casement",
    "w": 30,
    "h": 60,
    "d": 3
  },
  {
    "c": "CAS3072",
    "n": "Casement 30x72",
    "cat": "casement",
    "w": 30,
    "h": 72,
    "d": 3
  },
  {
    "c": "CAS3636",
    "n": "Casement 36x36",
    "cat": "casement",
    "w": 36,
    "h": 36,
    "d": 2
  },
  {
    "c": "CAS3648",
    "n": "Casement 36x48",
    "cat": "casement",
    "w": 36,
    "h": 48,
    "d": 2
  },
  {
    "c": "CAS3660",
    "n": "Casement 36x60",
    "cat": "casement",
    "w": 36,
    "h": 60,
    "d": 2
  },
  {
    "c": "CAS3672",
    "n": "Casement 36x72",
    "cat": "casement",
    "w": 36,
    "h": 72,
    "d": 3
  },
  {
    "c": "DH2846",
    "n": "Double-Hung 28x46",
    "cat": "double-hung",
    "w": 28,
    "h": 46,
    "d": 1,
    "hw": [
      {
        "t": "Verify the rough opening",
        "d": "Width at 3 points, height at 2, both diagonals. A double-hung binds fast if the sill is not level — fix the opening, never force the frame."
      },
      {
        "t": "Set the sill dead level",
        "d": "Shim at the setting points only, snug not tight. The sill is where a hung window lives or dies."
      },
      {
        "t": "Set and check reveal",
        "d": "Even reveal on all four sides before fastening. A tapered reveal tells you which corner is off."
      },
      {
        "t": "Fasten per schedule, re-check square",
        "d": "One over-driven screw racks the frame and drops the sashes. Check diagonals after each side."
      },
      {
        "t": "Flash jambs then head, foam light",
        "d": "Laps shed downhill. Low-expansion foam in passes so the jambs do not bow and jam the balances."
      }
    ]
  },
  {
    "c": "DH2852",
    "n": "Double-Hung 28x52",
    "cat": "double-hung",
    "w": 28,
    "h": 52,
    "d": 2
  },
  {
    "c": "DH2862",
    "n": "Double-Hung 28x62",
    "cat": "double-hung",
    "w": 28,
    "h": 62,
    "d": 2
  },
  {
    "c": "DH3246",
    "n": "Double-Hung 32x46",
    "cat": "double-hung",
    "w": 32,
    "h": 46,
    "d": 2
  },
  {
    "c": "DH3252",
    "n": "Double-Hung 32x52",
    "cat": "double-hung",
    "w": 32,
    "h": 52,
    "d": 1,
    "t": [
      "Drain slots on the bottom face OUT - confirm before lifting it in.",
      "Flash the sides first, top flashing last over the flange lip.",
      "Caulk flanges left/right/top, never the bottom - the bottom has to drain.",
      "Level first, then center. Set the flange screws, then remove the shims.",
      "Check both sashes slide before you screw off - a racked frame binds a double-hung fast."
    ],
    "x": [
      "Do not seal the bottom weep holes - a double-hung will pond water if you do.",
      "Confirm stucco vs rock setout before install.",
      "On hot days ease off screw torque on vinyl frames."
    ]
  },
  {
    "c": "DH3262",
    "n": "Double-Hung 32x62",
    "cat": "double-hung",
    "w": 32,
    "h": 62,
    "d": 2
  },
  {
    "c": "DH3646",
    "n": "Double-Hung 36x46",
    "cat": "double-hung",
    "w": 36,
    "h": 46,
    "d": 2
  },
  {
    "c": "DH3652",
    "n": "Double-Hung 36x52",
    "cat": "double-hung",
    "w": 36,
    "h": 52,
    "d": 2
  },
  {
    "c": "DH3662",
    "n": "Double-Hung 36x62",
    "cat": "double-hung",
    "w": 36,
    "h": 62,
    "d": 2
  },
  {
    "c": "DH4046",
    "n": "Double-Hung 40x46",
    "cat": "double-hung",
    "w": 40,
    "h": 46,
    "d": 2
  },
  {
    "c": "DH4052",
    "n": "Double-Hung 40x52",
    "cat": "double-hung",
    "w": 40,
    "h": 52,
    "d": 2
  },
  {
    "c": "DH4062",
    "n": "Double-Hung 40x62",
    "cat": "double-hung",
    "w": 40,
    "h": 62,
    "d": 2
  },
  {
    "c": "GAR3636",
    "n": "Garden 36x36",
    "cat": "specialty",
    "w": 36,
    "h": 36,
    "d": 4
  },
  {
    "c": "GAR3648",
    "n": "Garden 36x48",
    "cat": "specialty",
    "w": 36,
    "h": 48,
    "d": 4
  },
  {
    "c": "GAR4836",
    "n": "Garden 48x36",
    "cat": "specialty",
    "w": 48,
    "h": 36,
    "d": 4
  },
  {
    "c": "GAR4848",
    "n": "Garden 48x48",
    "cat": "specialty",
    "w": 48,
    "h": 48,
    "d": 4
  },
  {
    "c": "HOP2418",
    "n": "Hopper 24x18",
    "cat": "hopper",
    "w": 24,
    "h": 18,
    "d": 2
  },
  {
    "c": "HOP2424",
    "n": "Hopper 24x24",
    "cat": "hopper",
    "w": 24,
    "h": 24,
    "d": 2
  },
  {
    "c": "HOP3018",
    "n": "Hopper 30x18",
    "cat": "hopper",
    "w": 30,
    "h": 18,
    "d": 2
  },
  {
    "c": "HOP3024",
    "n": "Hopper 30x24",
    "cat": "hopper",
    "w": 30,
    "h": 24,
    "d": 2,
    "t": [
      "Hopper opens inward at the top - confirm swing clearance inside before setting.",
      "Drain side out; flash sides first, top flashing last over the flange lip.",
      "Level first - a racked hopper will not seal at the sill.",
      "Caulk flanges left/right/top, leave the bottom to drain.",
      "Test the latch and full open/close before final caulk."
    ],
    "x": [
      "Common in basements/wells - verify the well drains so the unit does not sit in water.",
      "Confirm setout depth (stucco vs rock).",
      "Do not seal the bottom weep holes."
    ]
  },
  {
    "c": "HOP3618",
    "n": "Hopper 36x18",
    "cat": "hopper",
    "w": 36,
    "h": 18,
    "d": 2
  },
  {
    "c": "HOP3624",
    "n": "Hopper 36x24",
    "cat": "hopper",
    "w": 36,
    "h": 24,
    "d": 2
  },
  {
    "c": "PIC3636",
    "n": "Picture 36x36",
    "cat": "picture",
    "w": 36,
    "h": 36,
    "d": 2
  },
  {
    "c": "PIC3648",
    "n": "Picture 36x48",
    "cat": "picture",
    "w": 36,
    "h": 48,
    "d": 2
  },
  {
    "c": "PIC3660",
    "n": "Picture 36x60",
    "cat": "picture",
    "w": 36,
    "h": 60,
    "d": 3
  },
  {
    "c": "PIC3672",
    "n": "Picture 36x72",
    "cat": "picture",
    "w": 36,
    "h": 72,
    "d": 3
  },
  {
    "c": "PIC4836",
    "n": "Picture 48x36",
    "cat": "picture",
    "w": 48,
    "h": 36,
    "d": 2
  },
  {
    "c": "PIC4848",
    "n": "Picture 48x48",
    "cat": "picture",
    "w": 48,
    "h": 48,
    "d": 2,
    "t": [
      "Stationary unit - no moving parts, so the finish caulk is the whole quality story.",
      "Drain side out; flash sides first, top flashing last over the flange lip.",
      "Level and center - with no sash to hide it, an out-of-level picture window shows.",
      "Exterior finish caulk is permanent: tape a ~3/4 in gap, caulk, then tool one smooth line.",
      "Photograph the finished caulk line and that all tape/stickers are removed."
    ],
    "x": [
      "Sloppy tooling on the exterior caulk is the most common callback on picture windows.",
      "Confirm setout depth (stucco vs rock).",
      "Big glass = 2-person lift; keep clear of the drop zone."
    ]
  },
  {
    "c": "PIC4860",
    "n": "Picture 48x60",
    "cat": "picture",
    "w": 48,
    "h": 60,
    "d": 3
  },
  {
    "c": "PIC4872",
    "n": "Picture 48x72",
    "cat": "picture",
    "w": 48,
    "h": 72,
    "d": 3
  },
  {
    "c": "PIC6036",
    "n": "Picture 60x36",
    "cat": "picture",
    "w": 60,
    "h": 36,
    "d": 2
  },
  {
    "c": "PIC6048",
    "n": "Picture 60x48",
    "cat": "picture",
    "w": 60,
    "h": 48,
    "d": 3,
    "t": [
      "Stationary - the exterior caulk finish is the whole job quality; take your time tooling it.",
      "2-person lift; set the bottom in, tilt up, drain side facing out.",
      "Flash sides first, top flashing last over the flange lip.",
      "Level and center; caulk flanges left/right/top, leave the bottom to drain.",
      "Photograph the final caulk line and confirm tape/stickers removed."
    ],
    "x": [
      "Tooling quality varies by installer - a bumpy caulk line is a visible defect.",
      "Confirm stucco vs rock setout.",
      "Keep clear of suspended glass during the lift."
    ]
  },
  {
    "c": "PIC6060",
    "n": "Picture 60x60",
    "cat": "picture",
    "w": 60,
    "h": 60,
    "d": 3,
    "hw": [
      {
        "t": "Confirm glass spec and safety bug",
        "d": "A large picture unit is heavy and often tempered/laminated. Check the etched bug and recalc crew/lift gear before it comes up."
      },
      {
        "t": "Dry-fit and stage on A-frames",
        "d": "Set on edge, never flat — a fixed lite this size will pop its IGU seal if racked during handling."
      },
      {
        "t": "Set on blocks, center the reveal",
        "d": "Setting blocks at the quarter points carry the weight. Center the unit so the perimeter joint is uniform for backer rod."
      },
      {
        "t": "Anchor without racking",
        "d": "Fixed units still rack. Fasten progressively and keep diagonals equal; a racked picture unit shows as a wavy reflection."
      },
      {
        "t": "Backer rod + tooled sealant",
        "d": "Rod to half the joint width, tool the same day. Big lites move a lot thermally — the joint must stretch, not shear."
      }
    ]
  },
  {
    "c": "PIC6072",
    "n": "Picture 60x72",
    "cat": "picture",
    "w": 60,
    "h": 72,
    "d": 3
  },
  {
    "c": "PIC7236",
    "n": "Picture 72x36",
    "cat": "picture",
    "w": 72,
    "h": 36,
    "d": 3
  },
  {
    "c": "PIC7248",
    "n": "Picture 72x48",
    "cat": "picture",
    "w": 72,
    "h": 48,
    "d": 3
  },
  {
    "c": "PIC7260",
    "n": "Picture 72x60",
    "cat": "picture",
    "w": 72,
    "h": 60,
    "d": 3
  },
  {
    "c": "PIC7272",
    "n": "Picture 72x72",
    "cat": "picture",
    "w": 72,
    "h": 72,
    "d": 3
  },
  {
    "c": "SH2846",
    "n": "Single-Hung 28x46",
    "cat": "single-hung",
    "w": 28,
    "h": 46,
    "d": 1
  },
  {
    "c": "SH2852",
    "n": "Single-Hung 28x52",
    "cat": "single-hung",
    "w": 28,
    "h": 52,
    "d": 1
  },
  {
    "c": "SH2862",
    "n": "Single-Hung 28x62",
    "cat": "single-hung",
    "w": 28,
    "h": 62,
    "d": 1
  },
  {
    "c": "SH3246",
    "n": "Single-Hung 32x46",
    "cat": "single-hung",
    "w": 32,
    "h": 46,
    "d": 1
  },
  {
    "c": "SH3252",
    "n": "Single-Hung 32x52",
    "cat": "single-hung",
    "w": 32,
    "h": 52,
    "d": 1,
    "t": [
      "Find the drain slots on the bottom of the frame - that side faces OUT. Never set it drain-side in.",
      "Flash both sides before you set the window; roll the TOP flashing last, over the flange lip, so water sheds down.",
      "Caulk the flanges left, right and top only - leave the bottom open so trapped water can drain.",
      "Shim and level first, center second. Level always wins. Set screws through the flanges, then pull the shims.",
      "St. George standard: caulk off the top and side weep holes, leave the bottom drains open."
    ],
    "x": [
      "Out-of-level wall: shim to true level even if the reveal looks uneven - flag the foreman if it is more than ~1 in off.",
      "Confirm stucco vs rock before setting depth - it changes the setout ~1 in (rock) vs ~1.5 in (stucco).",
      "Vinyl softens in high heat - do not overdrive screws or force a bind on hot days."
    ]
  },
  {
    "c": "SH3262",
    "n": "Single-Hung 32x62",
    "cat": "single-hung",
    "w": 32,
    "h": 62,
    "d": 1
  },
  {
    "c": "SH3646",
    "n": "Single-Hung 36x46",
    "cat": "single-hung",
    "w": 36,
    "h": 46,
    "d": 1
  },
  {
    "c": "SH3652",
    "n": "Single-Hung 36x52",
    "cat": "single-hung",
    "w": 36,
    "h": 52,
    "d": 1
  },
  {
    "c": "SH3662",
    "n": "Single-Hung 36x62",
    "cat": "single-hung",
    "w": 36,
    "h": 62,
    "d": 1
  },
  {
    "c": "SH4046",
    "n": "Single-Hung 40x46",
    "cat": "single-hung",
    "w": 40,
    "h": 46,
    "d": 1
  },
  {
    "c": "SH4052",
    "n": "Single-Hung 40x52",
    "cat": "single-hung",
    "w": 40,
    "h": 52,
    "d": 1
  },
  {
    "c": "SH4062",
    "n": "Single-Hung 40x62",
    "cat": "single-hung",
    "w": 40,
    "h": 62,
    "d": 1
  },
  {
    "c": "SL4836",
    "n": "Slider 48x36",
    "cat": "slider",
    "w": 48,
    "h": 36,
    "d": 3
  },
  {
    "c": "SL4848",
    "n": "Slider 48x48",
    "cat": "slider",
    "w": 48,
    "h": 48,
    "d": 3
  },
  {
    "c": "SL4860",
    "n": "Slider 48x60",
    "cat": "slider",
    "w": 48,
    "h": 60,
    "d": 3
  },
  {
    "c": "SL6036",
    "n": "Slider 60x36",
    "cat": "slider",
    "w": 60,
    "h": 36,
    "d": 3
  },
  {
    "c": "SL6040",
    "n": "Slider 60x40",
    "cat": "slider",
    "w": 60,
    "h": 40,
    "d": 3
  },
  {
    "c": "SL6048",
    "n": "Slider 60x48",
    "cat": "slider",
    "w": 60,
    "h": 48,
    "d": 3,
    "t": [
      "This is a 2-person lift - use suction cups or straps. Set the bottom into the frame, then tilt up.",
      "Get it dead level before screwing off or the panels will not roll smoothly.",
      "Drain side out; flash sides first, top flashing last over the flange lip.",
      "Caulk flanges left/right/top, leave the bottom to drain.",
      "Roll both panels full travel before final caulk to confirm no bind."
    ],
    "x": [
      "A racked slider binds - level and square matter more here than on a small window.",
      "Never get under a suspended panel during the lift.",
      "Confirm stucco vs rock setout before setting depth."
    ]
  },
  {
    "c": "SL6060",
    "n": "Slider 60x60",
    "cat": "slider",
    "w": 60,
    "h": 60,
    "d": 3
  },
  {
    "c": "SL7236",
    "n": "Slider 72x36",
    "cat": "slider",
    "w": 72,
    "h": 36,
    "d": 4
  },
  {
    "c": "SL7248",
    "n": "Slider 72x48",
    "cat": "slider",
    "w": 72,
    "h": 48,
    "d": 3,
    "t": [
      "Large slider - plan a 2-person lift with the suction machine; never solo it.",
      "Level and square are everything - test-roll the panels before you commit screws.",
      "Drain out; flash the sides, then top flashing last over the flange.",
      "Shim to level, set flange screws, pull shims, re-check the roll.",
      "Caulk flanges left/right/top only; leave the bottom open."
    ],
    "x": [
      "Heavy glass - keep everyone clear of the drop zone and the suction path.",
      "A slightly racked large slider will not seal or roll - do not accept it.",
      "Confirm the suction-cup machine is on site before scheduling this unit."
    ]
  },
  {
    "c": "SL7260",
    "n": "Slider 72x60",
    "cat": "slider",
    "w": 72,
    "h": 60,
    "d": 4
  },
  {
    "c": "SL8436",
    "n": "Slider 84x36",
    "cat": "slider",
    "w": 84,
    "h": 36,
    "d": 4
  },
  {
    "c": "SL8448",
    "n": "Slider 84x48",
    "cat": "slider",
    "w": 84,
    "h": 48,
    "d": 4
  },
  {
    "c": "SL8460",
    "n": "Slider 84x60",
    "cat": "slider",
    "w": 84,
    "h": 60,
    "d": 4
  },
  {
    "c": "TRANS2412",
    "n": "Transom 24x12",
    "cat": "picture",
    "w": 24,
    "h": 12,
    "d": 2
  },
  {
    "c": "TRANS2418",
    "n": "Transom 24x18",
    "cat": "picture",
    "w": 24,
    "h": 18,
    "d": 2
  },
  {
    "c": "TRANS3012",
    "n": "Transom 30x12",
    "cat": "picture",
    "w": 30,
    "h": 12,
    "d": 2
  },
  {
    "c": "TRANS3018",
    "n": "Transom 30x18",
    "cat": "picture",
    "w": 30,
    "h": 18,
    "d": 2
  },
  {
    "c": "TRANS3612",
    "n": "Transom 36x12",
    "cat": "picture",
    "w": 36,
    "h": 12,
    "d": 2
  },
  {
    "c": "TRANS3618",
    "n": "Transom 36x18",
    "cat": "picture",
    "w": 36,
    "h": 18,
    "d": 2
  }
];

/** When this snapshot was read out of the catalog. Shown as the brain's age. */
export const CATALOG_SNAPSHOT_AT = "2026-07-29T19:56:27Z";
