/**
 * The single registry of query-key ROOTS used anywhere in the app.
 *
 * The first element of every TanStack Query key is a root string — this is
 * the table that says what it is and whether the phone keeps it. A root
 * missing from here is a bug: `queryKeys.test.ts` scans app/src for every
 * root actually used in `queryKey:` / `setQueryData` / `getQueryData` calls
 * and fails, by name, on anything not registered here — and fails again if
 * this table lists a root nothing uses. Registering a new root means
 * answering one question: does the phone keep it offline? The `why` field
 * on each `offline: true` entry is the answer, carried over from the field
 * incident that put it there.
 *
 * `OFFLINE_KEY_ROOTS`, derived below, is what `queryClient.ts` persists to
 * localStorage. Flip `offline` here and the persister follows — there is no
 * second list to remember to update.
 */
export interface QueryKeyRootEntry {
  root: string;
  /** Does the phone keep this query when it has no signal? */
  offline: boolean;
  /**
   * The field incident (or reasoning) that decided the flag above, in the
   * repo's own voice. Required in spirit for every `offline: true` entry;
   * optional for `false` ones that have never needed a reason yet.
   */
  why?: string;
}

/**
 * Every query-key root in app/src, one row each. Alphabetical — this is a
 * lookup table, not a narrative; the incident comments that used to sit
 * beside the hand-kept offline list now live in each row's `why`.
 */
export const QUERY_KEY_ROOTS: QueryKeyRootEntry[] = [
  { root: "accessRequests", offline: false },
  { root: "aiSpendOverview", offline: false },
  { root: "allActiveCostCodes", offline: false },
  { root: "allCostCodes", offline: false },
  { root: "appFeedback", offline: false },
  { root: "askQuestionLog", offline: false },
  { root: "bankImports", offline: false },
  { root: "bankTransactions", offline: false },
  { root: "buildFacts", offline: true, why: "S4: the job facts card reads offline the same as the rest of the unit sheet — an installer standing at a wall with no signal still needs to know it's stucco and outset." },
  { root: "capabilityBadges", offline: false },
  { root: "certifications", offline: false },
  { root: "chatMentions", offline: false },
  { root: "chatRoster", offline: false },
  { root: "chatUnread", offline: false },
  { root: "checkoutReasons", offline: false },
  { root: "clearances", offline: false },
  { root: "clockCostCodes", offline: false },
  { root: "clockSkewMs", offline: false },
  { root: "clockedInAnywhere", offline: false },
  { root: "clockedInOnJob", offline: false },
  { root: "cohortEvidence", offline: false },
  { root: "companyCosting", offline: false },
  { root: "companySettings", offline: false },
  { root: "containerMovements", offline: false },
  { root: "costCodes", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "crateCount", offline: false },
  { root: "cratePool", offline: false },
  { root: "crewAccess", offline: false },
  { root: "crewInvites", offline: false },
  { root: "dailyLog", offline: false },
  { root: "dailyLogDraft", offline: false },
  { root: "dailyLogs", offline: false },
  { root: "dataHubBundles", offline: false },
  { root: "dataOffByProject", offline: false },
  { root: "dayMemoryLogs", offline: false },
  { root: "dayMemorySessions", offline: false },
  { root: "dayMemoryShifts", offline: false },
  { root: "deliveries", offline: true, why: "The tailgate in a yard with no signal (wave 4): what truck is coming and what is on its list, read from the last good copy." },
  { root: "deliveryCounts", offline: false },
  { root: "deliveryPackages", offline: true, why: "The tailgate in a yard with no signal (wave 4): what truck is coming and what is on its list, read from the last good copy." },
  { root: "dispatch", offline: false },
  { root: "educationProgress", offline: false },
  { root: "elevationViews", offline: true, why: "The flat map's two other reads (ticket 05, 2026-09-06): the traced building outline and the elevation views the pins hang off. The openings were cached and these were not, so the map offline drew pins on nothing." },
  { root: "failedInstalls", offline: false },
  { root: "failedWrites", offline: false },
  { root: "flashAlarms", offline: false },
  { root: "flashRunners", offline: false },
  { root: "fleetFinancials", offline: false },
  { root: "fleetServiceRecords", offline: false },
  { root: "foremanContacts", offline: false },
  { root: "gcCheckins", offline: false },
  { root: "gcCheckinsLatest", offline: false },
  { root: "gcLink", offline: false },
  { root: "gcThread", offline: false },
  { root: "grantableJobs", offline: false },
  { root: "greenLightItems", offline: false },
  { root: "heartbeat", offline: false },
  { root: "heartbeatGreenLightOpen", offline: false },
  { root: "homeGreenLightOpen", offline: false },
  { root: "homeTodayCrews", offline: false },
  { root: "incidents", offline: false },
  { root: "installerLeaderboard", offline: false },
  { root: "installerTypeStats", offline: false },
  { root: "isPartnerUser", offline: false },
  { root: "issuePhotoUrls", offline: false },
  { root: "issueRefs", offline: false },
  { root: "issues", offline: true },
  { root: "jobCosts", offline: false },
  { root: "jobDocumentAssetIds", offline: false },
  { root: "jobDocuments", offline: false },
  { root: "jobLastGeo", offline: false },
  { root: "jobLastGeos", offline: false },
  { root: "jobNotes", offline: false },
  { root: "jobVariance", offline: false },
  { root: "jobsNeedingLog", offline: false },
  { root: "knowledgeDocs", offline: false },
  { root: "learnProgress", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "learningTimeReport", offline: false },
  { root: "learningVideoReport", offline: false },
  { root: "learningVideos", offline: false },
  { root: "ledger", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "liveSummonsAll", offline: false },
  { root: "locations", offline: true, why: "Shelf and bin addresses. Without these a supply with a home spot degrades to \"home spot set\" — which looks configured and tells nobody where to go, in the conex where the answer matters most." },
  { root: "markSpecTypes", offline: false },
  { root: "markSpecs", offline: true, why: "The same law, one step on (installer research item 2, 2026-09-04): the fact that says WHAT to install has to be as durable as the facts that clear the gates around it. The spec card — sizes, hardware, the OXXO layout, the paperwork somebody reads standing at the opening — was the one thing the unit sheet could not show with no signal, and the \"no spec sheet for this mark\" notice is itself gated on the spec list being non-empty, so offline the installer got silence instead of a reason. An installer who can read the spec checks it; one who cannot, guesses." },
  { root: "memosToConfirm", offline: false },
  { root: "mondayIncoming", offline: false },
  { root: "mondayJobForProject", offline: false },
  { root: "movementsSince", offline: false },
  { root: "myActivePhases", offline: false },
  { root: "myFlashRuns", offline: false },
  { root: "myId", offline: false },
  { root: "myLearningTime", offline: false },
  { root: "myOpeningBlocks", offline: false },
  { root: "myOpenings", offline: true },
  { root: "myPinStatus", offline: false },
  { root: "myProfile", offline: true },
  { root: "myReadyCount", offline: false },
  { root: "myRealProfile", offline: false },
  { root: "mySchedule", offline: false },
  { root: "myScheduleVehicles", offline: false },
  { root: "myShifts", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "myTimecardEdits", offline: false },
  { root: "myWorkedJobs", offline: false },
  { root: "notifDismissed", offline: false },
  { root: "notifReorder", offline: false },
  { root: "notifReorderProjects", offline: false },
  { root: "notifScheduleConflicts", offline: false },
  { root: "notifVehicles", offline: false },
  { root: "openRedos", offline: false },
  { root: "openShift", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "opening", offline: true },
  { root: "openingAssignments", offline: false },
  { root: "openingNotes", offline: false },
  { root: "openingPhases", offline: true, why: "Same shape of bug as toolboxToday, found on review 2026-09-02: the OPENING was cached (so `needs_flashing = true` came back after an offline reload) and the flashing phase row that CLEARS it was not. A unit whose flashing was already done then read as still owing it, Submit went dead with no way out, and the install could not even be queued for later. The fact that clears a gate has to be as offline-durable as the fact that raises it." },
  { root: "openingPhotoCounts", offline: false },
  { root: "openingRedos", offline: false },
  { root: "openingRefs", offline: false },
  { root: "openingSessions", offline: false },
  { root: "openings", offline: true },
  { root: "orders", offline: false },
  { root: "overtimeRules", offline: false },
  { root: "packageEvents", offline: false },
  { root: "packagePhotos", offline: false },
  { root: "partTypeOptions", offline: false },
  { root: "partnerInvites", offline: false },
  { root: "partnerJobGrants", offline: false },
  { root: "partnerLogins", offline: false },
  { root: "payPeriodShifts", offline: false },
  { root: "payRates", offline: false },
  { root: "phasePhoto", offline: false },
  { root: "photos", offline: false },
  { root: "photos-trash", offline: false },
  { root: "pinMoves", offline: false },
  { root: "planOutlines", offline: true, why: "The flat map's two other reads (ticket 05, 2026-09-06): the traced building outline and the elevation views the pins hang off. The openings were cached and these were not, so the map offline drew pins on nothing." },
  { root: "planUnderlayImage", offline: false },
  { root: "plansetProgress", offline: false },
  { root: "plansets", offline: true },
  { root: "pointsLeaderboard", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "priorityTerms", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "profileName", offline: false },
  { root: "profiles", offline: false },
  { root: "profilesAll", offline: false },
  { root: "profilesIncludingRemoved", offline: false },
  { root: "projectAssignments", offline: false },
  { root: "projectCostCodes", offline: false },
  { root: "projectExceptions", offline: false },
  { root: "projectIssues", offline: false },
  { root: "projectMessages", offline: false },
  { root: "projectRoster", offline: false },
  { root: "projectSchedule", offline: false },
  { root: "projectUnits", offline: false },
  { root: "projectVehicleLinks", offline: false },
  { root: "projectWindows", offline: true },
  { root: "projects", offline: true },
  { root: "projectsAll", offline: true, why: "Every job, whatever its status. The unit sheet sits behind a guard that asks this list whether the job is tracking-only (RequireDataJob in App.tsx), and a guard that cannot answer holds a loading screen. Offline that read never resolves — with no connection react-query PAUSES the retry instead of failing it, so the query stays pending for as long as the phone has no signal — and the sheet the whole install loop runs on sat at \"Loading…\" the entire time. Found by the offline e2e spec, 2026-09-04." },
  { root: "projectsTrashed", offline: false },
  { root: "qcInstalled", offline: false },
  { root: "qcPassed", offline: false },
  { root: "qcQueue", offline: false },
  { root: "qcStatusForOpenings", offline: false },
  { root: "receiptJobSuggestions", offline: false },
  { root: "receipts-feed", offline: false },
  { root: "receipts-office", offline: false },
  { root: "recentJobs", offline: false },
  { root: "recordEvents", offline: false },
  { root: "recordMedia", offline: false },
  { root: "removedOpenings", offline: false },
  { root: "reorderNeeds", offline: false },
  { root: "savedCrews", offline: false },
  { root: "schedule", offline: false },
  { root: "scheduleAssignments", offline: false },
  { root: "scheduleCoverage", offline: false },
  { root: "scheduleDrafts", offline: false },
  { root: "scheduledMarks", offline: true },
  { root: "scopeCounts", offline: true },
  { root: "search", offline: false },
  { root: "serverNowMs", offline: false },
  { root: "serviceCases", offline: false },
  { root: "serviceCasesAll", offline: false },
  { root: "serviceRefs", offline: false },
  { root: "shiftEdits", offline: false },
  { root: "shiftsToApprove", offline: false },
  { root: "specDiscrepancyAcks", offline: false },
  { root: "stgCalendar", offline: false },
  { root: "stgDay", offline: false },
  { root: "stgJobList", offline: false },
  { root: "storageBlanks", offline: false },
  { root: "storageContainers", offline: true, why: "\"Where is it?\" from the last good read. Same reason as storagePackages — ticket 10's conex reading problem, ticket 06's move off `inventory`." },
  { root: "storagePackage", offline: false },
  { root: "storagePackages", offline: true, why: "\"Where is it?\" from the last good read. A conex is a metal box with no bars, and the harder half of working in one is READING — you have to find things in there, not just record what you took (ticket 10). The hub's numbers moved off `inventory` onto packages in ticket 06, so this and storageContainers are what the Find bar and the cards actually need." },
  { root: "studioJobModelStates", offline: false },
  { root: "studioJobModels", offline: false },
  { root: "studioProject", offline: false },
  { root: "studioProjects", offline: false },
  { root: "studioUnits", offline: false },
  { root: "summonDeclines", offline: false },
  { root: "summonHelpers", offline: false },
  { root: "summons", offline: false },
  { root: "supplies", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "supply-takes", offline: false },
  { root: "takeoffs", offline: false },
  { root: "talkAssignments", offline: false },
  { root: "talkDays", offline: false },
  { root: "talkLibrary", offline: false },
  { root: "teamShifts", offline: false },
  { root: "teamShifts30d", offline: false },
  { root: "timecardInstalls", offline: false },
  { root: "timecardMine", offline: false },
  { root: "timecardPanel", offline: false },
  { root: "timecardPeriod", offline: false },
  { root: "todayTalk", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "toolboxCompliance", offline: false },
  { root: "toolboxHistory", offline: true },
  { root: "toolboxToday", offline: true, why: "The talk itself was cached but not whether YOU signed it, so after an offline reload the app could see a talk exists and not that the gate was already cleared — every Start install silently refused, with no message, for as long as there was no signal. That is the exact situation the offline work exists for (installer audit, 2026-08-17)." },
  { root: "tools", offline: true, why: "New modules — keep the installer's day usable in dead spots." },
  { root: "tracePlanImage", offline: false },
  { root: "trip", offline: true, why: "Travel Info — assigned trips must be viewable in transit / dead zones." },
  { root: "trips", offline: true, why: "Travel Info — assigned trips must be viewable in transit / dead zones." },
  { root: "typeBrain", offline: true },
  { root: "undoneInstalls", offline: false },
  { root: "unfinishedShifts", offline: false },
  { root: "unitMovements", offline: false },
  { root: "unitSearch", offline: false },
  { root: "unitSessions", offline: false },
  { root: "vaultPinStatus", offline: false },
  { root: "vehicle", offline: false },
  { root: "vehicleDriveSessions", offline: false },
  { root: "vehicleFinancials", offline: false },
  { root: "vehicleLinks", offline: false },
  { root: "vehicleService", offline: false },
  { root: "vehicles", offline: false },
  { root: "videoQuiz", offline: false },
  { root: "videoQuizPublic", offline: false },
  { root: "voidedOpenings", offline: false },
  { root: "weeklyLogCoverage", offline: false },
  { root: "windowTypes", offline: true },
];

/**
 * The roots the phone keeps in its persisted cache, derived from the table
 * above rather than hand-kept — this is what used to be `OFFLINE_KEYS` in
 * queryClient.ts.
 */
export const OFFLINE_KEY_ROOTS: ReadonlySet<string> = new Set(
  QUERY_KEY_ROOTS.filter((entry) => entry.offline).map((entry) => entry.root),
);

/**
 * Build a query key for new code. Does not enforce that `root` is
 * registered above — TypeScript cannot check a runtime table like that —
 * but `queryKeys.test.ts` does, on every root actually used in the app, so
 * an unregistered root still fails, just at test time instead of compile
 * time.
 */
export function qk(root: string, ...parts: unknown[]): readonly unknown[] {
  return [root, ...parts];
}

