#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Backblaze B2 for the nightly backup (Forge Windows and Doors)
#
# Source of truth: docs/backups.md "Setting up Backblaze" and the two
# workflows that read the secrets, .github/workflows/backup-nightly.yml and
# restore-test.yml. Three repository secrets turn the off-site copy on:
# B2_KEY_ID, B2_APPLICATION_KEY, B2_BUCKET. Until they exist the nightly runs
# but nothing leaves the runner (a public repo's artifacts are public).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
export GH_REPO="Infinity-Windows/infinity-windows"   # gh acts on this repo wherever you run from
ENV_FILE="${B2_WIZARD_ENV:-$HOME/.config/infinity-windows/b2-wizard.env}"   # remembers the bucket name only; keys are never written to disk
mkdir -p "$(dirname "$ENV_FILE")"

banner "Backblaze B2 — nightly backup, off-site"

# The application key is shown once. Make sure gh can store it BEFORE Backblaze shows it.
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "Sign in to GitHub first: run   gh auth login   (GitHub.com, HTTPS), then re-run this wizard."
  exit 1
fi

# ── 1 ── the bucket ────────────────────────────────────────────────────────
stage "Backblaze — create the bucket"
say "One private bucket holds every night's sealed archive."
open_url "https://secure.backblaze.com/b2_buckets.htm"
step "Press 'Create a Bucket'."
step "Bucket Unique Name: forge-windows-backups (names are global — add a suffix if it is taken)."
step "Files in Bucket: PRIVATE. Leave Default Encryption and Object Lock at their defaults."
step "Press 'Create a Bucket'."
ask B2_BUCKET "Type the bucket name exactly as Backblaze shows it:"
while [[ -z "$B2_BUCKET" ]]; do warn "the bucket name cannot be empty"; ask B2_BUCKET "Bucket name:"; done
write_env B2_BUCKET "$B2_BUCKET"

# ── 2 ── the lifecycle rule ───────────────────────────────────────────────
stage "Backblaze — the rule that keeps 30 days"
say "Without this rule the bucket grows forever while looking handled."
note "The obvious choice, 'Keep only the last version', deletes NOTHING here: every night"
note "writes a new dated file name, so no file ever gets an older version to expire."
step "On the Buckets page find $B2_BUCKET and press 'Lifecycle Settings'."
step "Choose 'Use custom lifecycle rules' and add ONE rule:"
step "   File Name Prefix: leave EMPTY (the rule covers the whole bucket)"
step "   Days Till Hide:   30"
step "   Days Till Delete: 1"
step "Press 'Update Bucket'."
pause "Press Enter once the rule shows 30 / 1 on the bucket…"
if ! confirm "Does the bucket's lifecycle now read 'Days Till Hide: 30, Days Till Delete: 1'?"; then
  warn "Go back and fix it now — the nightly cost depends on it."
  pause "Press Enter when it does…"
fi

# ── 3 ── the application key ──────────────────────────────────────────────
stage "Backblaze — one key, scoped to this bucket"
say "The key is shown ONCE. Have this window ready before you press Create."
open_url "https://secure.backblaze.com/app_keys.htm"
step "Press 'Add a New Application Key'."
step "Name of Key: github-nightly-backup"
step "Allow access to Bucket(s): choose $B2_BUCKET — NOT 'All'."
step "Type of Access: Read and Write."
step "File name prefix and Duration: leave empty. Press 'Create New Key'."
step "Copy keyID and applicationKey from the green box now — closing it hides them for good."
ask_secret B2_KEY_ID "Paste the keyID (typing is hidden):"
ask_secret B2_APPLICATION_KEY "Paste the applicationKey (typing is hidden):"
while [[ -z "$B2_KEY_ID" || -z "$B2_APPLICATION_KEY" ]]; do
  warn "both values are needed"
  ask_secret B2_KEY_ID "keyID:"; ask_secret B2_APPLICATION_KEY "applicationKey:"
done
note "Neither value is written to disk by this wizard; they go straight to GitHub in the next stage."

# ── 4 ── the three GitHub secrets ─────────────────────────────────────────
stage "GitHub — three repository secrets"
say "These are the exact names backup-nightly.yml and restore-test.yml read."
set_secret B2_KEY_ID "$B2_KEY_ID"
set_secret B2_APPLICATION_KEY "$B2_APPLICATION_KEY"
set_secret B2_BUCKET "$B2_BUCKET"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  missing=0
  for n in B2_KEY_ID B2_APPLICATION_KEY B2_BUCKET BACKUP_PASSPHRASE; do
    if gh secret list 2>/dev/null | awk '{print $1}' | grep -qx "$n"; then say "✓ $n is set"; else warn "$n is NOT set"; missing=1; fi
  done
  (( missing )) && warn "Set the missing one(s) by hand: Settings → Secrets and variables → Actions."
else
  warn "gh is not signed in here — set the three secrets by hand (names above), then continue."
  pause
fi
unset B2_KEY_ID B2_APPLICATION_KEY   # the values leave this shell now

# ── 5 ── prove it: one backup by hand ────────────────────────────────────
stage "GitHub — run 'Nightly backup' once, by hand"
say "A green check is not a backup. The job summary must say the copy went off-site."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 && confirm "Start the Nightly backup workflow now?"; then
  if gh workflow run backup-nightly.yml >/dev/null 2>&1; then
    say "Started. It takes a few minutes; watching for it to finish…"
    sleep 20
    RUN_ID=$(gh run list --workflow backup-nightly.yml --limit 1 --json databaseId --jq '.[0].databaseId' 2>/dev/null || true)
    if [[ -n "$RUN_ID" ]]; then
      gh run watch "$RUN_ID" --exit-status >/dev/null 2>&1 && say "✓ the run finished green" || warn "the run did not finish green — open it and read the summary"
      gh run view "$RUN_ID" --web >/dev/null 2>&1 || true
    fi
  else
    warn "could not start it from here"
  fi
fi
open_url "https://github.com/Infinity-Windows/infinity-windows/actions/workflows/backup-nightly.yml"
step "If the wizard did not start a run: press 'Run workflow', keep branch master, press 'Run workflow' again, and wait for it to finish."
step "Open the newest run and read its Summary. It must say 'Copied off-site to <bucket>/YYYY/MM/DD/' and 'Sealed with BACKUP_PASSPHRASE'."
step "If it says nothing left the runner, a secret is wrong or missing. A key cannot be shown twice: re-run this wizard from the top, and at stage 3 press 'Add a New Application Key' again (delete the old one on that page), so stage 4 sets all three afresh."
pause "Press Enter once the summary says the copy went off-site…"

# ── 6 ── see the file with your own eyes ─────────────────────────────────
stage "Backblaze — the file is really there"
open_url "https://secure.backblaze.com/b2_buckets.htm"
step "In the left menu under B2 Cloud Storage press 'Browse Files', pick $B2_BUCKET, then open today's YYYY → MM → DD folder."
step "There should be one file ending in .tar.gz.enc, a few MB or more, dated today."
if confirm "Do you see today's .tar.gz.enc file in the bucket?"; then
  say "✓ That is the first real off-site backup this company has had."
else
  warn "Then the summary and the bucket disagree — send the run link to Claude."
fi
say ""
say "Two things to keep somewhere safe, outside GitHub:"
step "BACKUP_PASSPHRASE — in the password manager. Without it no archive can be opened."
step "The July copy of docs/backups in your laptop's clone — keep it on an encrypted disk (it holds crew emails), but know it has database dumps and plansets only, no install photos. The run you just made is the first copy of those."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 && confirm "Also run the Sunday 'Restore test' now, to prove the copy can be opened and replayed?"; then
  gh workflow run restore-test.yml >/dev/null 2>&1 && say "✓ started — it posts to Slack only if something is wrong; a pass sits in its summary" || warn "could not start it from here"
fi

finish
