#!/usr/bin/env python3
"""Regenerate the bundled window-catalog snapshot the offline brain searches.

The brain has to answer with the phone in airplane mode, so the real (non
provisional) catalog ships inside the app bundle instead of being fetched. This
script reads the catalog straight out of a Supabase project, read-only, and
writes app/src/lib/brain/catalogSnapshot.ts.

Usage:
    SUPABASE_ACCESS_TOKEN=... scripts/gen-brain-snapshot.py [project-ref]

The generated file is committed, so the repo stays the source of truth and CI
never needs database credentials.
"""

from __future__ import annotations

import json
import os
import pathlib
import sys
import urllib.request

DEFAULT_REF = "czprjcskmzzagdztqonm"

QUERY = """
select json_agg(row_to_json(t) order by t.type_code) as rows
from (
  select type_code, name, category, width_in, height_in,
         difficulty_rating, notes, tips_json, watch_outs_json, howto_json
  from window_types
  where provisional = false
) t;
"""

OUT = pathlib.Path(__file__).resolve().parent.parent / "app/src/lib/brain/catalogSnapshot.ts"

HEADER = """// GENERATED by scripts/gen-brain-snapshot.py — do not edit by hand.
//
// The real (non-provisional) window catalog, bundled so the offline brain can
// answer type questions with no signal. Provisional rows — the "Mark #1" units
// spec extraction creates — are excluded on purpose: they are not catalog
// products and they pollute search. Keys are short to keep the payload small.
import type { CatalogType } from "./types";

export const CATALOG_SNAPSHOT: CatalogType[] = """

FOOTER = """;

/** When this snapshot was read out of the catalog. Shown as the brain's age. */
export const CATALOG_SNAPSHOT_AT = %s;
"""


def num(value):
    if value is None:
        return None
    f = float(value)
    return int(f) if f.is_integer() else f


def compact(row: dict) -> dict:
    out: dict = {"c": row["type_code"], "n": row["name"]}
    for key, src in (("cat", "category"), ("note", "notes")):
        if row.get(src):
            out[key] = row[src]
    for key, src in (("w", "width_in"), ("h", "height_in")):
        value = num(row.get(src))
        if value is not None:
            out[key] = value
    if row.get("difficulty_rating") is not None:
        out["d"] = row["difficulty_rating"]
    for key, src in (("t", "tips_json"), ("x", "watch_outs_json")):
        if row.get(src):
            out[key] = row[src]
    howto = row.get("howto_json") or []
    steps = [
        {"t": s["title"], "d": s.get("detail", "")}
        for s in howto
        if isinstance(s, dict) and s.get("title")
    ]
    if steps:
        out["hw"] = steps
    return out


def main() -> int:
    token = os.environ.get("SUPABASE_ACCESS_TOKEN", "").strip()
    if not token:
        print("SUPABASE_ACCESS_TOKEN is required", file=sys.stderr)
        return 2
    ref = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_REF

    request = urllib.request.Request(
        f"https://api.supabase.com/v1/projects/{ref}/database/query",
        data=json.dumps({"query": QUERY, "read_only": True}).encode(),
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            # The management API rejects urllib's default agent.
            "User-Agent": "infinity-windows/gen-brain-snapshot",
        },
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        payload = json.load(response)
    rows = payload[0]["rows"] or []
    if not rows:
        print("no non-provisional window types came back — refusing to write", file=sys.stderr)
        return 1

    body = json.dumps([compact(r) for r in rows], indent=2, ensure_ascii=False)
    generated_at = json.dumps(
        __import__("datetime").datetime.now(__import__("datetime").timezone.utc)
        .strftime("%Y-%m-%dT%H:%M:%SZ")
    )
    OUT.write_text(HEADER + body + (FOOTER % generated_at), encoding="utf-8")
    tips = sum(len(r.get("tips_json") or []) + len(r.get("watch_outs_json") or []) for r in rows)
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}: {len(rows)} types, {tips} tip lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
