#!/usr/bin/env node
// Generate a realistic ~100-type window catalog with dimensions + difficulty.
// Writes docs/window-catalog-100.csv and docs/window-catalog-100.sql (upsert).
// The fit check needs real width_in/height_in per type; this stands in until
// the shop's true catalog is loaded.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// prefix, name, category, widths, heights, difficulty(w,h)->1-5
const families = [
  { p: "SH", name: "Single-Hung", cat: "single-hung", w: [28, 32, 36, 40], h: [46, 52, 62], diff: () => 1 },
  { p: "DH", name: "Double-Hung", cat: "double-hung", w: [28, 32, 36, 40], h: [46, 52, 62], diff: () => 2 },
  { p: "CAS", name: "Casement", cat: "casement", w: [24, 30, 36], h: [36, 48, 60, 72], diff: (w, h) => (h >= 60 ? 3 : 2) },
  { p: "AWN", name: "Awning", cat: "awning", w: [24, 30, 36, 42], h: [18, 24, 30], diff: () => 2 },
  { p: "HOP", name: "Hopper", cat: "hopper", w: [24, 30, 36], h: [18, 24], diff: () => 2 },
  { p: "TRANS", name: "Transom", cat: "picture", w: [24, 30, 36], h: [12, 18], diff: () => 2 },
  { p: "SL", name: "Slider", cat: "slider", w: [48, 60, 72, 84], h: [36, 48, 60], diff: (w) => (w >= 72 ? 4 : 3) },
  { p: "PIC", name: "Picture", cat: "picture", w: [36, 48, 60, 72], h: [36, 48, 60, 72], diff: (w, h) => (w >= 72 || h >= 60 ? 3 : 2) },
  { p: "GAR", name: "Garden", cat: "specialty", w: [36, 48], h: [36, 48], diff: () => 4 },
  { p: "BAY", name: "Bay", cat: "specialty", w: [72, 96], h: [48, 60], diff: () => 5 },
  { p: "BOW", name: "Bow", cat: "specialty", w: [96, 120], h: [48, 60], diff: () => 5 },
];

const rows = [];
for (const f of families) {
  for (const w of f.w) {
    for (const h of f.h) {
      const code = `${f.p}${w}${h}`;
      rows.push({
        type_code: code,
        name: `${f.name} ${w}x${h}`,
        category: f.cat,
        width_in: w,
        height_in: h,
        difficulty_rating: f.diff(w, h),
        tutorial_url: "",
        notes: "",
      });
    }
  }
}

const header = "type_code,name,category,width_in,height_in,difficulty_rating,tutorial_url,notes";
const csv = [header, ...rows.map((r) =>
  [r.type_code, r.name, r.category, r.width_in, r.height_in, r.difficulty_rating, r.tutorial_url, r.notes].join(","),
)].join("\n") + "\n";

const esc = (s) => (s == null || s === "" ? "null" : `'${String(s).replace(/'/g, "''")}'`);
const values = rows
  .map((r) => `  (${esc(r.type_code)}, ${esc(r.name)}, ${esc(r.category)}, ${r.width_in}, ${r.height_in}, ${r.difficulty_rating})`)
  .join(",\n");
const sql = `-- Generated by scripts/generate-catalog.mjs — ${rows.length} window types with dimensions.
insert into window_types (type_code, name, category, width_in, height_in, difficulty_rating) values
${values}
on conflict (type_code) do update set
  name = excluded.name,
  category = excluded.category,
  width_in = excluded.width_in,
  height_in = excluded.height_in,
  difficulty_rating = coalesce(window_types.difficulty_rating, excluded.difficulty_rating);
`;

mkdirSync(join(root, "docs"), { recursive: true });
writeFileSync(join(root, "docs", "window-catalog-100.csv"), csv);
writeFileSync(join(root, "docs", "window-catalog-100.sql"), sql);
console.log(`Wrote ${rows.length} types to docs/window-catalog-100.csv and .sql`);
