#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

REPO="Infinity-Windows/infinity-windows"
OLD_URL="https://infinity-windows.github.io/infinity-windows/"

banner "Forge Windows and Doors — go live on your own domain"

# ── Stage 1: buy the domain ────────────────────────────────────────────────
stage "Buy the domain"
say "The app is already live at:"
say "  $OLD_URL"
say "This wizard moves it onto a domain you own. First, buy one."
say ""
step "Recommended: Cloudflare Registrar — domains at cost, no markup, and"
step "its DNS panel (used in the next stage) is fast and free."
step "Fine too: Namecheap or Porkbun, if you'd rather a simpler checkout."
open_url "https://dash.cloudflare.com/?to=/:account/registrar/register"
say ""
warn "I can't buy it for you — purchases and payment details are yours."
step "Buy the domain, then come back here."
ask DOMAIN "What domain did you buy? (like infinitywindows.com):"
write_env DOMAIN "$DOMAIN"
say ""
say "Where should the app live on it?"
step "app.$DOMAIN  — recommended. Keeps the bare domain free for a future"
step "                public website; the crew taps an icon, not a URL."
step "$DOMAIN      — the bare domain itself, if you want it all app."
if confirm "Use app.$DOMAIN (recommended)?"; then
  APP_HOST="app.$DOMAIN"
  HOST_MODE="subdomain"
else
  APP_HOST="$DOMAIN"
  HOST_MODE="apex"
fi
write_env APP_HOST "$APP_HOST"
write_env HOST_MODE "$HOST_MODE"

# ── Stage 2: point DNS at GitHub Pages ─────────────────────────────────────
stage "Point the domain at GitHub Pages"
say "In your registrar's DNS panel for $DOMAIN, add:"
say ""
if [[ "$HOST_MODE" == "subdomain" ]]; then
  step "One CNAME record:  name 'app'  →  target 'infinity-windows.github.io'"
else
  step "Four A records on the bare domain (@), one per address:"
  step "  185.199.108.153   185.199.109.153"
  step "  185.199.110.153   185.199.111.153"
  step "Plus one CNAME:  name 'www'  →  target 'infinity-windows.github.io'"
fi
note "On Cloudflare: set the record to 'DNS only' (grey cloud, NOT orange)."
note "The orange proxy blocks GitHub from issuing the HTTPS certificate."
open_url "https://dash.cloudflare.com"
pause "Records saved? Press Enter and I'll check them."
say ""
say "Checking DNS (new records can take 5–30 minutes to show up)…"
while true; do
  if [[ "$HOST_MODE" == "subdomain" ]]; then
    got=$(dig +short "$APP_HOST" CNAME | head -1)
    if [[ "$got" == *"github.io"* ]]; then
      say "${GREEN}✓ $APP_HOST points at GitHub Pages.${RESET}"; break
    fi
  else
    got=$(dig +short "$APP_HOST" A | head -1)
    if [[ "$got" == 185.199.* ]]; then
      say "${GREEN}✓ $APP_HOST points at GitHub Pages.${RESET}"; break
    fi
  fi
  warn "Not seeing it yet (got: ${got:-nothing})."
  confirm "Wait a minute and check again?" || break
  sleep 60
done

# ── Stage 3: make sure every phone is synced ───────────────────────────────
stage "Sync gate — before anything moves"
say "The app queues offline changes ON THE PHONE, tied to the old address."
say "Anything still queued when we switch stays behind and never sends."
say ""
step "Have everyone open the app: the top-right badge must say 'All synced'."
step "You check Stuck writes too:"
open_url "${OLD_URL}stuck"
say ""
warn "Evening is the best time for the rest of this — nobody mid-shift."
confirm "Every phone synced — safe to switch?" || { warn "Stopping here. Re-run when ready — your answers are saved."; exit 0; }

# ── Stage 4: tell GitHub about the domain ──────────────────────────────────
stage "GitHub — custom domain + the build switch"
say "Two changes, both made for you right now:"
step "1. GitHub Pages learns the domain (settings change via gh)."
step "2. The repo variable PAGES_DOMAIN flips the next build to serve it."
say ""
if gh api -X PUT "repos/$REPO/pages" -f cname="$APP_HOST" >/dev/null 2>&1; then
  say "${GREEN}✓ Pages custom domain set to $APP_HOST${RESET}"
else
  warn "Couldn't set it via gh. Do it by hand:"
  step "Repo → Settings → Pages → Custom domain → $APP_HOST → Save"
  open_url "https://github.com/$REPO/settings/pages"
  pause "Done?"
fi
set_var PAGES_DOMAIN "$APP_HOST"
say ""
say "Waiting for GitHub to verify DNS and issue the HTTPS certificate"
say "(usually 1–15 minutes)…"
while true; do
  https_state=$(gh api "repos/$REPO/pages" --jq '.https_certificate.state' 2>/dev/null || echo "unknown")
  say "  certificate: $https_state"
  [[ "$https_state" == "approved" || "$https_state" == "issued" ]] && break
  confirm "Not ready yet. Wait a minute and check again?" || break
  sleep 60
done
if gh api -X PUT "repos/$REPO/pages" -F https_enforced=true >/dev/null 2>&1; then
  say "${GREEN}✓ HTTPS enforced — http:// visits bounce to https://${RESET}"
else
  warn "Tick 'Enforce HTTPS' by hand on the Pages settings page once it's clickable."
fi

# ── Stage 5: ship the build that lives on the domain ───────────────────────
stage "Deploy the switch"
say "Kicking off the deploy that builds the app for $APP_HOST…"
if gh workflow run "Deploy GitHub Pages" --ref master >/dev/null 2>&1; then
  say "${GREEN}✓ Deploy started${RESET}"
else
  warn "Couldn't start it via gh — merge any PR to master and it deploys itself."
fi
say "Waiting for it to finish (about 2 minutes)…"
sleep 30
while true; do
  state=$(gh run list --repo "$REPO" --workflow "Deploy GitHub Pages" --limit 1 --json status,conclusion --jq '.[0].status + "/" + (.[0].conclusion // "-")' 2>/dev/null || echo unknown)
  say "  deploy: $state"
  [[ "$state" == "completed/success" ]] && break
  if [[ "$state" == completed/* ]]; then warn "Deploy finished badly ($state) — stop and investigate."; break; fi
  sleep 20
done
say ""
say "Proving the site answers:"
code=$(curl -s -o /dev/null -w '%{http_code}' "https://$APP_HOST/" || echo 000)
if [[ "$code" == "200" ]]; then
  say "${GREEN}✓ https://$APP_HOST/ answers 200 — the app is live on your domain.${RESET}"
else
  warn "Got HTTP $code — give the certificate a few more minutes and re-run this stage."
fi

# ── Stage 6: Supabase — teach the backend the new address ──────────────────
stage "Supabase — login and email links"
say "Password-reset emails and logins must point at the new address."
open_url "https://supabase.com/dashboard"
step "Open your project → Authentication → URL Configuration."
step "Site URL:  https://$APP_HOST/"
step "Redirect URLs — add BOTH:"
step "  https://$APP_HOST/**"
step "  http://localhost:5173/**"
note "Keep the old github.io entry listed for now — old emails still resolve."
pause "Saved?"

# ── Stage 7: Supabase — real email service (the rate-limit fix) ────────────
stage "Email — stop the two-an-hour cap"
say "Supabase's built-in mailer is for TESTING: it sends a couple of emails"
say "an hour, total, then refuses — you hit this cap after two reset tries."
say "The limit can only be raised after plugging in a real mail service."
say ""
step "Make a free Resend account (3,000 emails/month free):"
open_url "https://resend.com"
step "In Resend: verify your domain $DOMAIN (they show the DNS records to"
step "add — same registrar panel as stage 2), then create an API key."
step "In Supabase: Project Settings → Auth → SMTP Settings → enable Custom"
step "SMTP and fill in Resend's host/port/user/key. Sender: no-reply@$DOMAIN"
open_url "https://supabase.com/dashboard"
step "Then Authentication → Rate Limits → set 'emails per hour' to 30."
note "30/hour covers every reset and invite a crew your size sends, with"
note "room to spare. The app itself also rests the reset button between"
note "tries now, so nobody burns the quota by double-tapping."
pause "SMTP saved and the rate limit set?"

# ── Stage 8: Supabase — check the plan ─────────────────────────────────────
stage "Supabase — make sure the backend can't pause"
say "Free Supabase projects PAUSE after about a week without traffic —"
say "for a company running its whole day on this, that's not acceptable."
step "Project → Settings → Billing: if it says Free, upgrade to Pro (~\$25/mo)."
open_url "https://supabase.com/dashboard"
confirm "Plan checked (Pro, or you've decided Free is fine for now)?" || true

# ── Stage 9: prove it end to end on your phone ─────────────────────────────
stage "Prove it on a real phone"
step "Open https://$APP_HOST/ on your phone."
step "Sign in. Add it to your home screen. Allow notifications when asked."
step "Then the reset-link round trip: sign out → 'Reset password' → open the"
step "email → the link must land on the 'Set a new password' screen."
say ""
say "Old bookmarks keep working — GitHub now redirects the old address:"
curl -sI "$OLD_URL" | head -1 | sed 's/^/  /'
pause "All good on the phone?"

# ── Stage 10: tell the crew ────────────────────────────────────────────────
stage "Tell the crew"
say "Send everyone something like this:"
say ""
say "  The app moved to its real home: https://$APP_HOST/"
say "  1. Open that link on your phone."
say "  2. Sign in again (one time — the move resets logins)."
say "  3. Add it to your home screen, and allow notifications."
say "  4. Delete the old icon."
say ""
warn "Two more crew notes from the audit:"
step "Any crew invite links sent but NOT yet redeemed were minted on the old"
step "address — re-send those invites from the Crew access screen."
step "Notification opt-ins don't move between addresses (a phone rule, not"
step "ours) — step 3 above re-creates them, so don't skip it."
say ""
say "From now on: every PR merged to master goes live on the domain"
say "automatically — frontend and backend both, same as before."
note "Rollback if ever needed: gh variable delete PAGES_DOMAIN, clear the"
note "custom domain on the Pages settings page, and redeploy."

finish
