-- Exact revision2 contract. Seed is a reviewed assembly constant, not live drift.
create table public.work_cross_job_contract (
 proof_key text primary key check(proof_key='cross_job_kernel_2'),
 expected_catalog_sha256 text not null check(expected_catalog_sha256 ~ '^[0-9a-f]{64}$')
);
revoke all on table public.work_cross_job_contract from public,anon,authenticated,service_role;
alter table public.work_cross_job_contract enable row level security;
create function public._work_cross_job_coverage() returns boolean language sql stable security definer set search_path=public,pg_temp as $coverage$
 select coalesce((select count(*)=1 and bool_and(proof_key='cross_job_kernel_2' and expected_catalog_sha256 ~ '^[0-9a-f]{64}$' and expected_catalog_sha256=encode(sha256(convert_to(c.value::text,'UTF8')),'hex')) from public.work_cross_job_contract),false) from (
-- Deliberately closed source-derived public catalog. Unknown live drift refuses;
-- this is not a request to normalize a provider to the disposable fixture.
select jsonb_build_object(
 'types',(select jsonb_agg(jsonb_build_object('name',t.typname,'kind',t.typtype,'owner',pg_get_userbyid(t.typowner),'acl',t.typacl::text,'category',t.typcategory,'preferred',t.typispreferred,'defined',t.typisdefined,'notNull',t.typnotnull,'base',format_type(nullif(t.typbasetype,0),t.typtypmod),'element',format_type(nullif(t.typelem,0),null),'collation',case when t.typcollation<>0 then t.typcollation::regcollation::text end,'default',t.typdefault,'defaultExpression',pg_get_expr(t.typdefaultbin,0),'input',t.typinput::regprocedure::text,'output',t.typoutput::regprocedure::text,'receive',t.typreceive::regprocedure::text,'send',t.typsend::regprocedure::text,'length',t.typlen,'byValue',t.typbyval,'alignment',t.typalign,'storage',t.typstorage,'delimiter',t.typdelim,'access',(select jsonb_object_agg(r.rolname,has_type_privilege(r.oid,t.oid,'USAGE')) from pg_roles r where r.rolname in('anon','authenticated','service_role')),'enum',(select jsonb_agg(jsonb_build_object('label',e.enumlabel,'sort',e.enumsortorder) order by e.enumsortorder) from pg_enum e where e.enumtypid=t.oid),'constraints',(select jsonb_agg(jsonb_build_object('name',k.conname,'definition',pg_get_constraintdef(k.oid,true),'validated',k.convalidated) order by k.conname) from pg_constraint k where k.contypid=t.oid),'range',(select jsonb_build_object('subtype',format_type(r.rngsubtype,null),'collation',r.rngcollation::regcollation::text,'opclass',(select n.nspname||'.'||o.opcname from pg_opclass o join pg_namespace n on n.oid=o.opcnamespace where o.oid=r.rngsubopc),'canonical',r.rngcanonical::regprocedure::text,'subdiff',r.rngsubdiff::regprocedure::text) from pg_range r where r.rngtypid=t.oid)) order by t.typname) from pg_type t where t.typnamespace='public'::regnamespace),
 'sequences',(select jsonb_agg(jsonb_build_object('name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'type',format_type(s.seqtypid,null),'start',s.seqstart,'increment',s.seqincrement,'max',s.seqmax,'min',s.seqmin,'cache',s.seqcache,'cycle',s.seqcycle,'access',(select jsonb_agg(jsonb_build_object('role',r.rolname,'privilege',v.p,'allowed',has_sequence_privilege(r.oid,c.oid,v.p)) order by r.rolname,v.p) from pg_roles r cross join unnest(array['SELECT','UPDATE','USAGE'])v(p) where r.rolname in('anon','authenticated','service_role'))) order by c.relname) from pg_class c join pg_sequence s on s.seqrelid=c.oid where c.relnamespace='public'::regnamespace),
 'foreignTables',(select jsonb_agg(jsonb_build_object('table',c.relname,'options',f.ftoptions,'server',s.srvname,'serverOwner',pg_get_userbyid(s.srvowner),'serverType',s.srvtype,'serverVersion',s.srvversion,'serverOptionsDigest',encode(sha256(convert_to(coalesce(s.srvoptions::text,''),'UTF8')),'hex'),'serverAcl',s.srvacl::text,'serverAccess',(select jsonb_object_agg(r.rolname,has_server_privilege(r.oid,s.oid,'USAGE')) from pg_roles r where r.rolname in('anon','authenticated','service_role')),'wrapper',w.fdwname,'wrapperOwner',pg_get_userbyid(w.fdwowner),'wrapperAcl',w.fdwacl::text,'wrapperAccess',(select jsonb_object_agg(r.rolname,has_foreign_data_wrapper_privilege(r.oid,w.oid,'USAGE')) from pg_roles r where r.rolname in('anon','authenticated','service_role')),'handler',w.fdwhandler::regprocedure::text,'validator',w.fdwvalidator::regprocedure::text,'wrapperOptionsDigest',encode(sha256(convert_to(coalesce(w.fdwoptions::text,''),'UTF8')),'hex')) order by c.relname) from pg_foreign_table f join pg_class c on c.oid=f.ftrelid join pg_foreign_server s on s.oid=f.ftserver join pg_foreign_data_wrapper w on w.oid=s.srvfdw where c.relnamespace='public'::regnamespace),
 'functions',(select jsonb_agg(jsonb_build_object('name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'body',encode(sha256(convert_to(p.prosrc,'UTF8')),'hex'),'result',pg_get_function_result(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'language',l.lanname,'kind',p.prokind,'definer',p.prosecdef,'config',p.proconfig,'volatility',p.provolatile,'strict',p.proisstrict,'leakproof',p.proleakproof,'cost',p.procost,'rows',p.prorows,'support',p.prosupport::regprocedure::text,'parallel',p.proparallel,'defaults',pg_get_expr(p.proargdefaults,0),'access',(select jsonb_object_agg(r.rolname,has_function_privilege(r.oid,p.oid,'EXECUTE')) from pg_roles r where r.rolname in('anon','authenticated','service_role'))) order by p.proname,pg_get_function_identity_arguments(p.oid)) from pg_proc p join pg_language l on l.oid=p.prolang where p.pronamespace='public'::regnamespace and not exists(select 1 from pg_depend d where d.classid='pg_proc'::regclass and d.objid=p.oid and d.deptype='e')),
 'relations',(select jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'forcedRls',c.relforcerowsecurity,'acl',c.relacl::text,'access',(select jsonb_agg(jsonb_build_object('role',r.rolname,'privilege',v.p,'table',has_table_privilege(r.oid,c.oid,v.p),'column',case when v.p in('SELECT','INSERT','UPDATE','REFERENCES') then has_any_column_privilege(r.oid,c.oid,v.p) end) order by r.rolname,v.p) from pg_roles r cross join unnest(array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'])v(p) where r.rolname in('anon','authenticated','service_role'))) order by c.relname) from pg_class c where c.relnamespace='public'::regnamespace and c.relkind in('r','p','v','m','f','c')),
 'columns',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notNull',a.attnotnull,'generated',a.attgenerated,'identity',a.attidentity,'acl',a.attacl::text,'default',pg_get_expr(d.adbin,d.adrelid),'access',(select jsonb_agg(jsonb_build_object('role',r.rolname,'privilege',v.p,'allowed',has_column_privilege(r.oid,c.oid,a.attnum,v.p)) order by r.rolname,v.p) from pg_roles r cross join unnest(array['SELECT','INSERT','UPDATE','REFERENCES'])v(p) where r.rolname in('anon','authenticated','service_role'))) order by c.relname,a.attnum) from pg_class c join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where c.relnamespace='public'::regnamespace and c.relkind in('r','p','v','m','f','c')),
 'constraints',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',k.conname,'definition',pg_get_constraintdef(k.oid,true),'validated',k.convalidated,'noInherit',k.connoinherit,'enforced',coalesce((to_jsonb(k)->>'conenforced')::boolean,true)) order by c.relname,k.conname) from pg_constraint k join pg_class c on c.oid=k.conrelid where c.relnamespace='public'::regnamespace and k.contype<>'n'),
 'notNullConstraints',(select jsonb_agg(jsonb_build_object('table',c.relname,'column',a.attname,'validated',coalesce(n.validated,true),'enforced',coalesce(n.enforced,true),'noInherit',coalesce(n.no_inherit,false)) order by c.relname,a.attnum) from pg_class c join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped left join lateral(select bool_and(k.convalidated) validated,bool_and(coalesce((to_jsonb(k)->>'conenforced')::boolean,true)) enforced,bool_or(k.connoinherit) no_inherit from pg_constraint k where k.conrelid=c.oid and k.contype='n' and a.attnum=any(k.conkey))n on true where c.relnamespace='public'::regnamespace and c.relkind in('r','p')),
 'indexes',(select jsonb_agg(jsonb_build_object('table',t.relname,'name',c.relname,'definition',pg_get_indexdef(i.indexrelid),'valid',i.indisvalid,'ready',i.indisready) order by t.relname,c.relname) from pg_index i join pg_class c on c.oid=i.indexrelid join pg_class t on t.oid=i.indrelid where t.relnamespace='public'::regnamespace),
 'triggers',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid,true),'enabled',t.tgenabled) order by c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid where c.relnamespace='public'::regnamespace and not t.tgisinternal),
 'policies',(select jsonb_agg(to_jsonb(p) order by p.tablename,p.policyname) from pg_policies p where schemaname='public'),
 'views',(select jsonb_agg(jsonb_build_object('name',c.relname,'definition',pg_get_viewdef(c.oid,true)) order by c.relname) from pg_class c where c.relnamespace='public'::regnamespace and c.relkind in('v','m'))
) value
)c
$coverage$;
revoke all on function public._work_cross_job_coverage() from public,anon,authenticated,service_role;
insert into public.work_cross_job_contract values('cross_job_kernel_2','00db48aa715a066d2c3cd0ec73423a8af14e7338fa2c13e36ab2ff68b49f307e');
create trigger work_cross_job_contract_immutable before insert or update or delete on public.work_cross_job_contract for each row execute function public.work_capture_immutable_record();
create trigger work_cross_job_contract_no_truncate before truncate on public.work_cross_job_contract for each statement execute function public.work_capture_immutable_record();
create or replace function public._work_unit_review_coverage() returns boolean language sql stable security definer set search_path=public,pg_temp as $$
 select (coalesce((select p.prosrc is not null and encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')='bbebab5cc374c8233ba85a865428db4ac38ed8e0c4bf8b295edf645bb4d8e074' and pg_get_userbyid(p.proowner)='postgres' and p.proacl::text='{postgres=X/postgres}' and p.prosecdef and p.proconfig=array['search_path=public, pg_temp']::text[] and p.provolatile='s' and not p.proisstrict and not p.proleakproof and p.proparallel='u' and p.prokind='f' and not p.proretset and p.prorettype='boolean'::regtype and p.pronargs=0 and p.pronargdefaults=0 and p.procost=100 and p.prorows=0 and p.prosupport=0 and p.prolang=(select oid from pg_language where lanname='sql') from pg_proc p where p.oid=to_regprocedure('public._work_cross_job_coverage()')),false) and public._work_cross_job_coverage()) and not exists(select 1 from public.work_cross_job_shifts)
$$;
revoke all on function public._work_unit_review_coverage() from public,anon,authenticated,service_role;
create or replace function public._work_totals_coverage() returns boolean language sql stable security definer set search_path=public,pg_temp as $$
 select (coalesce((select p.prosrc is not null and encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')='bbebab5cc374c8233ba85a865428db4ac38ed8e0c4bf8b295edf645bb4d8e074' and pg_get_userbyid(p.proowner)='postgres' and p.proacl::text='{postgres=X/postgres}' and p.prosecdef and p.proconfig=array['search_path=public, pg_temp']::text[] and p.provolatile='s' and not p.proisstrict and not p.proleakproof and p.proparallel='u' and p.prokind='f' and not p.proretset and p.prorettype='boolean'::regtype and p.pronargs=0 and p.pronargdefaults=0 and p.procost=100 and p.prorows=0 and p.prosupport=0 and p.prolang=(select oid from pg_language where lanname='sql') from pg_proc p where p.oid=to_regprocedure('public._work_cross_job_coverage()')),false) and public._work_cross_job_coverage()) and not exists(select 1 from public.work_cross_job_shifts)
$$;
revoke all on function public._work_totals_coverage() from public,anon,authenticated,service_role;
create or replace function public._work_unit_contributors_coverage() returns boolean language sql stable security definer set search_path=public,pg_temp as $$
 select (coalesce((select p.prosrc is not null and encode(sha256(convert_to(p.prosrc,'UTF8')),'hex')='bbebab5cc374c8233ba85a865428db4ac38ed8e0c4bf8b295edf645bb4d8e074' and pg_get_userbyid(p.proowner)='postgres' and p.proacl::text='{postgres=X/postgres}' and p.prosecdef and p.proconfig=array['search_path=public, pg_temp']::text[] and p.provolatile='s' and not p.proisstrict and not p.proleakproof and p.proparallel='u' and p.prokind='f' and not p.proretset and p.prorettype='boolean'::regtype and p.pronargs=0 and p.pronargdefaults=0 and p.procost=100 and p.prorows=0 and p.prosupport=0 and p.prolang=(select oid from pg_language where lanname='sql') from pg_proc p where p.oid=to_regprocedure('public._work_cross_job_coverage()')),false) and public._work_cross_job_coverage()) and not exists(select 1 from public.work_cross_job_shifts)
$$;
revoke all on function public._work_unit_contributors_coverage() from public,anon,authenticated,service_role;
