import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {parseAttemptEvidenceV1,parseCrossJobRecord,freezeCrossJobOriginal,crossJobHead,crossJobDelivery,consumeCrossJobSendV4,prepareCrossJobSendCheckV4} from './crossJobStorageV4';
import * as old from './crossJobStorageV3';
import {evidenceFixture} from './crossJobStorageV4.fixtures';
import {id,fences,genesis} from './crossJobStorageV3.fixtures';
describe('pure attempt envelope; complete existing RecordV3 parser, no DB/provider',()=>{
 it('uses the exact unchanged original/parser/head/delivery functions',()=>{expect(parseCrossJobRecord).toBe(old.parseCrossJobRecord);expect(freezeCrossJobOriginal).toBe(old.freezeCrossJobOriginal);expect(crossJobHead).toBe(old.crossJobHead);expect(crossJobDelivery).toBe(old.crossJobDelivery);});
 it.each([{kind:'not_invoked'} as const,{kind:'invoked',observedSqlError:null} as const,{kind:'invoked',observedSqlError:{source:'command_rpc_returned_error',code:'23514'}} as const,{kind:'invoked',observedSqlError:{source:'command_rpc_returned_error',code:'42501'}} as const])('roundtrips fact %j with immutable exact full original',fact=>{const {record,evidence}=evidenceFixture(fact);const parsed=parseAttemptEvidenceV1(evidence,record);expect(parsed).toEqual(evidence);expect(Object.isFrozen(parsed.fact)).toBe(true);expect(record.everAttempted).toBe(true);expect(parsed.originalCommandBytes).toBe(record.original.commandBytes);});
 it.each(['ownerId','deviceId','commandId','attemptToken','localLoginGeneration','originalCommandBytes'] as const)('rejects changed %s linkage',key=>{const {record,evidence}=evidenceFixture();const changed={...evidence,[key]:key==='localLoginGeneration'?3:key==='originalCommandBytes'?evidence.originalCommandBytes+' ':id(99)};expect(()=>parseAttemptEvidenceV1(changed,record)).toThrow();});
 it.each([0,1,3,2.5,Infinity,NaN])('rejects revision %s',settlementRevision=>{const {record,evidence}=evidenceFixture();expect(()=>parseAttemptEvidenceV1({...evidence,settlementRevision},record)).toThrow();});
 it('permits later hold revision without rewriting evidence',()=>{const {record,evidence}=evidenceFixture();expect(parseAttemptEvidenceV1(evidence,{...record,revision:3,hold:'context_changed'})).toEqual(evidence);});
 it.each([{extra:true},{encodingVersion:2},{fact:{kind:'not_invoked',observedSqlError:null}},{fact:{kind:'invoked',observedSqlError:{source:'command_rpc_returned_error',code:'XX000'}}},{fact:{kind:'refused'}}])('rejects extra/version/union drift %j',patch=>{const {record,evidence}=evidenceFixture();expect(()=>parseAttemptEvidenceV1({...evidence,...patch},record)).toThrow();});
 it('rejects original bytes and malformed entire record even when outer evidence matches',()=>{const {record,evidence}=evidenceFixture();const corrupt=structuredClone(record);corrupt.original.commandBytes='{}';expect(()=>parseAttemptEvidenceV1({...evidence,originalCommandBytes:'{}'},corrupt)).toThrow();expect(()=>parseAttemptEvidenceV1(evidence,{...record,everAttempted:false,attemptToken:null})).toThrow();});
 it('rejects ordinary data accessors without invoking them',()=>{const {record,evidence}=evidenceFixture();const getter=vi.fn(()=>id(1));Object.defineProperty(evidence,'ownerId',{get:getter,enumerable:true});expect(()=>parseAttemptEvidenceV1(evidence,record)).toThrow();expect(getter).not.toHaveBeenCalled();});
 it('structural ticket cannot consume or prepare, and causes no transaction',async()=>{const transaction=vi.fn(),db={transaction} as unknown as IDBDatabase,ticket={command:genesis().command,token:id(70)},context={expected:fences(),current:()=>fences()};expect(()=>consumeCrossJobSendV4(db,ticket)).toThrow();await expect(prepareCrossJobSendCheckV4(db,ticket,context)).rejects.toThrow();expect(transaction).not.toHaveBeenCalled();});
 it('the sole command RPC call is inside a non-exported journal invoker; adapter has no alternate path or observer hook',()=>{const source=readFileSync(new URL('./crossJobStorageV4.ts',import.meta.url),'utf8'),api=readFileSync(new URL('../workActivity/apiV3.ts',import.meta.url),'utf8');expect(source.match(/rpc\('work_activity_command'/g)).toHaveLength(1);expect(api).not.toContain('work_activity_command');expect(source).toMatch(/const invoke=[\s\S]*active\.invoked=true;\s*const pending=rpc\('work_activity_command'/);expect(source).not.toMatch(/export (?:async )?function invoke/);expect(source+api).not.toContain('observeInvokerForTest');expect(api).toContain('}finally{local.forfeit();}');});
});
